#pragma once

#pragma region Cody_Animation
#define C_ActionMH	1
#define C_ActionMH_To_Idle	2
#define C_AirDash_Start	3
#define C_Bhv_ArcadeScreenLever_Bck	4
#define C_Bhv_ArcadeScreenLever_BckLeft	5
#define C_Bhv_ArcadeScreenLever_BckRight	6
#define C_Bhv_ArcadeScreenLever_Fwd	7
#define C_Bhv_ArcadeScreenLever_FwdLeft	8
#define C_Bhv_ArcadeScreenLever_FwdRight	9
#define C_Bhv_ArcadeScreenLever_Left	10
#define C_Bhv_ArcadeScreenLever_MH	11
#define C_Bhv_ArcadeScreenLever_Right	12
#define C_Bhv_ArcadeScreenLever_Trigger	13
#define C_Bhv_Bounce_01	14
#define C_Bhv_Bounce_02	15
#define C_Bhv_Bounce_03	16
#define C_Bhv_Bounce_04	17
#define C_Bhv_Bump_Collide	18
#define C_Bhv_Bump_Collide_Fall	19
#define C_Bhv_ChagneSize_PlanetPush_Small	20
#define C_Bhv_ChangeSize_GroundPound_Falling	21
#define C_Bhv_ChangeSize_GroundPound_Land_Exit	22
#define C_Bhv_ChangeSize_GroundPound_Land_MH	23
#define C_Bhv_ChangeSize_GroundPound_Start	24
#define C_Bhv_ChangeSize_PlanetPush_Large	25
#define C_Bhv_ChangeSize_PlanetPush_Medium	26
#define C_Bhv_ChessMiniGame_Gestures_Point	27
#define C_Bhv_DashMoveTo_Start	28
#define C_Bhv_DashMoveTo_Start_InAir	29
#define C_Bhv_DashMoveTo_Start_Left90	30
#define C_Bhv_DashMoveTo_Start_Right90	31
#define C_Bhv_Death_Fall_MH	32
#define C_Bhv_Death_Oil_Drown	33
#define C_Bhv_FidgetSpinner_Enter	34
#define C_Bhv_FidgetSpinner_Exit	35
#define C_Bhv_FidgetSpinner_Hover_Fast_MH	36
#define C_Bhv_FidgetSpinner_Hover_Fast_MH_Left	37
#define C_Bhv_FidgetSpinner_Hover_Fast_MH_Right	38
#define C_Bhv_FidgetSpinner_Hover_Slow_MH	39
#define C_Bhv_FidgetSpinner_Hover_Slow_MH_Left	40
#define C_Bhv_FidgetSpinner_Hover_Slow_MH_Right	41
#define C_Bhv_FidgetSpinner_InAir_Enter	42
#define C_Bhv_FidgetSpinner_InAir_Exit	43
#define C_Bhv_Generic_WalkIn	44
#define C_Bhv_GroundPound_Falling	45
#define C_Bhv_GroundPound_Jump_High	46
#define C_Bhv_GroundPound_Jump_Low	47
#define C_Bhv_GroundPound_Land	48
#define C_Bhv_GroundPound_Land_Exit	49
#define C_Bhv_GroundPound_Land_MH	50
#define C_Bhv_GroundPound_Start	51
#define C_Bhv_HoldButton_Enter	52
#define C_Bhv_HoldButton_Exit	53
#define C_Bhv_HoldButton_MH	54
#define C_Bhv_Jump_Start	55
#define C_Bhv_KnockDown_Back_Land	56
#define C_Bhv_KnockDown_Back_MH	57
#define C_Bhv_KnockDown_Back_Start	58
#define C_Bhv_KnockDown_Front	59
#define C_Bhv_KnockDown_Front_Land	60
#define C_Bhv_KnockDown_Front_MH	61
#define C_Bhv_KnockDown_Front_Start	62
#define C_Bhv_KnockDown_Left_Land	63
#define C_Bhv_KnockDown_Left_MH	64
#define C_Bhv_KnockDown_Left_Start	65
#define C_Bhv_knockDown_Right_Land	66
#define C_Bhv_KnockDown_Right_MH	67
#define C_Bhv_KnockDown_Right_Start	68
#define C_Bhv_Lever_Left	69
#define C_Bhv_Lever_Right	70
#define C_Bhv_LeverPull_Exit_Fast	71
#define C_Bhv_LeverPull_Exit_Slow	72
#define C_Bhv_LeverPull_MH	73
#define C_Bhv_LeverPull_Start_Fast	74
#define C_Bhv_MH_Gesture_Big_Waiting_Enter	75
#define C_Bhv_MH_Gesture_Big_Waiting_MH	76
#define C_Bhv_MH_Gesture_Small_AdjustLeaf	77
#define C_Bhv_MH_Gesture_Small_Belly	78
#define C_Bhv_MH_Gesture_Small_Drumming	79
#define C_Bhv_MH_Gesture_Small_InspectNails	80
#define C_Bhv_MH_Gesture_Small_LookAround	81
#define C_Bhv_MH_Gesture_Small_Scratch	82
#define C_Bhv_MH_Gesture_Small_Stretch	83
#define C_Bhv_MH_Gesture_Small_TossLeaf	84
#define C_Bhv_MiniGame_Emotes_AssDance	85
#define C_Bhv_MiniGame_Emotes_CossackDance	86
#define C_Bhv_MiniGame_Emotes_Explosion	87
#define C_Bhv_MiniGame_Emotes_FistPump	88
#define C_Bhv_MiniGame_Emotes_Fonzie	89
#define C_Bhv_MiniGame_Emotes_HappyDance	90
#define C_Bhv_MiniGame_Emotes_Huzzah	91
#define C_Bhv_MiniGame_Emotes_JumpUpLand	92
#define C_Bhv_MiniGame_Emotes_KarateBow	93
#define C_Bhv_MiniGame_Emotes_LeafFlex	94
#define C_Bhv_MiniGame_Emotes_Lose_Var1	95
#define C_Bhv_MiniGame_Emotes_Lose_Var2	96
#define C_Bhv_MiniGame_Emotes_Lose_Var3	97
#define C_Bhv_MiniGame_Emotes_ShoulderBrush	98
#define C_Bhv_MiniGame_Emotes_WatchingYou	99
#define C_Bhv_MiniGame_Emotes_WeirdRobot	100
#define C_Bhv_PickUp	101
#define C_Bhv_PickUp_Aim_Strafe_Bwd	102
#define C_Bhv_PickUp_Aim_Strafe_Fwd	103
#define C_Bhv_PickUp_Aim_Strafe_Left	104
#define C_Bhv_PickUp_Aim_Strafe_Right	105
#define C_Bhv_PickUp_AimSpace_Center	106
#define C_Bhv_PickUp_AimSpace_Down	107
#define C_Bhv_pickUp_AimSpace_Up	108
#define C_Bhv_PickUp_FuseCrab_PutInSocket	109
#define C_Bhv_PickUp_Jog	110
#define C_Bhv_PickUp_Jog_Stop	111
#define C_Bhv_PickUp_Jump_Falling	112
#define C_Bhv_PickUp_Jump_Land	113
#define C_Bhv_PickUp_Jump_Land_Jog	114
#define C_Bhv_PickUp_MH	115
#define C_Bhv_PickUp_Throw	116
#define C_Bhv_PickUpHeavySmall_Jog	117
#define C_Bhv_PickUpHeavySmall_Jog_StartInMotion	118
#define C_Bhv_PickUpHeavySmall_Jog_Stop	119
#define C_Bhv_PickUpHeavySmall_Jump_Falling	120
#define C_Bhv_PickUpHeavySmall_Jump_Land	121
#define C_Bhv_PickUpHeavySmall_Jump_Land_Jog	122
#define C_Bhv_PickUpHeavySmall_Jump_Start	123
#define C_Bhv_PickUpHeavySmall_MH	124
#define C_Bhv_PickUpHeavySmall_PickUp	125
#define C_Bhv_PickUpHeavySmall_PutDown	126
#define C_Bhv_PickUpHeavySmall_PutDown_InPlace	127
#define C_Bhv_PickUpSmall	128
#define C_Bhv_PickUpSmall_Aim_MH	129
#define C_Bhv_PickUpSmall_Aim_Strafe_Fwd	130
#define C_Bhv_PickUpSmall_AimSpace_Down	131
#define C_Bhv_PickUpSmall_AimSpace_Up	132
#define C_Bhv_PickUpSmall_AirDashStart	133
#define C_Bhv_PickUpSmall_Bhv_GroundPound_Falling	134
#define C_Bhv_PickUpSmall_Bhv_GroundPound_Jump_High	135
#define C_Bhv_PickUpSmall_Bhv_GroundPound_Jump_Low	136
#define C_Bhv_PickUpSmall_Bhv_GroundPound_Land	137
#define C_Bhv_PickUpSmall_Bhv_GroundPound_Land_MH	138
#define C_Bhv_PickUpSmall_Bhv_GroundPound_Start	139
#define C_Bhv_PickUpSmall_Bhv_Swinging_Bck	140
#define C_Bhv_PickUpSmall_Bhv_Swinging_Bck_Bck	141
#define C_Bhv_PickUpSmall_Bhv_Swinging_Bck_Fwd	142
#define C_Bhv_PickUpSmall_Bhv_Swinging_Bck_Neutral	143
#define C_Bhv_PickUpSmall_Bhv_Swinging_Bck_TurnAround	144
#define C_Bhv_PickUpSmall_Bhv_Swinging_ExitBck	145
#define C_Bhv_PickUpSmall_Bhv_Swinging_ExitFwd	146
#define C_Bhv_PickUpSmall_Bhv_Swinging_Fwd	147
#define C_Bhv_PickUpSmall_Bhv_Swinging_JumpBck	148
#define C_Bhv_PickUpSmall_Bhv_Swinging_JumpFwd	149
#define C_Bhv_PickUpSmall_Bhv_Swinging_Neutral	150
#define C_Bhv_PickUpSmall_Bhv_Swinging_TurnAround	151
#define C_Bhv_PickUpSmall_Bounce_01	152
#define C_Bhv_PickUpSmall_Bounce_02	153
#define C_Bhv_PickUpSmall_Bounce_03	154
#define C_Bhv_PickUpSmall_Bounce_04	155
#define C_Bhv_PickUpSmall_DoubleJump	156
#define C_Bhv_PickUpSmall_Grind_Fast	157
#define C_Bhv_PickUpSmall_Grind_Fast_MH_Left	158
#define C_Bhv_PickUpSmall_Grind_Fast_MH_Right	159
#define C_Bhv_PickUpSmall_Grind_Grapple_Enter	160
#define C_Bhv_PickUpSmall_Grind_Grapple_ToGrind	161
#define C_Bhv_PickUpSmall_Grind_Jump	162
#define C_Bhv_PickUpSmall_Grind_Land	163
#define C_Bhv_PickUpSmall_Grind_Slow_MH	164
#define C_Bhv_PickUpSmall_Grind_Slow_MH_Left	165
#define C_Bhv_PickUpSmall_Grind_Slow_MH_Right	166
#define C_Bhv_PickUpSmall_Grind_TurnAround_Boost	167
#define C_Bhv_PickUpSmall_Grind_TurnAround_SlowDown	168
#define C_Bhv_PickUpSmall_Jog	169
#define C_Bhv_PickUpSmall_Jog_GoToStop	170
#define C_Bhv_PickUpSmall_Jog_Start_Fwd	171
#define C_Bhv_PickUpSmall_Jog_Start_InMotion	172
#define C_Bhv_PickUpSmall_Jog_Stop_Fwd	173
#define C_Bhv_PickUpSmall_Jump_Falling	174
#define C_Bhv_PickUpSmall_Jump_From_Landing	175
#define C_Bhv_PickUpSmall_Jump_Land	176
#define C_Bhv_PickUpSmall_Jump_Land_Jog	177
#define C_Bhv_PickUpSmall_Jump_Start	178
#define C_Bhv_PickUpSmall_Jump_StartFromStill	179
#define C_Bhv_PickUpSmall_LedgeGrab_ClimbUp	180
#define C_Bhv_PickUpSmall_LedgeGrab_Drop	181
#define C_Bhv_PickUpSmall_LedgeGrab_JumpBack_Left	182
#define C_Bhv_PickUpSmall_LedgeGrab_JumpUp	183
#define C_Bhv_PickUpSmall_LedgeGrab_MH	184
#define C_Bhv_PickUpSmall_LedgeGrab_MH_Left120	185
#define C_Bhv_PickUpSmall_LedgeGrab_MH_Left180	186
#define C_Bhv_PickUpSmall_LedgeGrab_MH_Left30	187
#define C_Bhv_PickUpSmall_LedgeGrab_MH_Left60	188
#define C_Bhv_PickUpSmall_LedgeGrab_MH_Left90	189
#define C_Bhv_PickUpSmall_LedgeGrab_Start	190
#define C_Bhv_PickUpSmall_LedgeVault	191
#define C_Bhv_PickUpSmall_LedgeVaultStart	192
#define C_Bhv_PickUpSmall_MH	193
#define C_Bhv_PickUpSmall_PerfectDash	194
#define C_Bhv_PickUpSmall_PerfectDashJog	195
#define C_Bhv_PickUpSmall_PerfectDashStop	196
#define C_Bhv_PickUpSmall_PutDown	197
#define C_Bhv_PickUpSmall_PutDown_InPlace	198
#define C_Bhv_PickUpSmall_Roll_Start	199
#define C_Bhv_PickUpSmall_Roll_Stop	200
#define C_Bhv_PickUpSmall_Roll_To_Jog	201
#define C_Bhv_PickUpSmall_Sprint	202
#define C_Bhv_PickUpSmall_SprintStartFromDash	203
#define C_Bhv_PickUpSmall_SprintTurnAround	204
#define C_Bhv_PickUpSmall_Strafe_Aim_Shuffle_Left	205
#define C_Bhv_PickUpSmall_Strafe_Aim_Shuffle_Right	206
#define C_Bhv_PickUpSmall_Strafe_AimSpace_Charge_Down	207
#define C_Bhv_PickUpSmall_Strafe_AimSpace_Charge_Up	208
#define C_Bhv_PickUpSmall_Strafe_Bwd	209
#define C_Bhv_PickUpSmall_Strafe_Bwd_L	210
#define C_Bhv_PickUpSmall_Strafe_Bwd_R	211
#define C_Bhv_PickUpSmall_Strafe_Fwd	212
#define C_Bhv_PickUpSmall_Strafe_Fwd_L	213
#define C_Bhv_PickUpSmall_Strafe_Fwd_R	214
#define C_Bhv_PickUpSmall_Strafe_Left	215
#define C_Bhv_PickUpSmall_Strafe_MH	216
#define C_Bhv_PickUpSmall_Strafe_Right	217
#define C_Bhv_PickUpSmall_Throw	218
#define C_Bhv_PickUpSmall_WallSlide_Enter	219
#define C_Bhv_PickUpSmall_WallSlide_Enter_FromDash	220
#define C_Bhv_PickUpSmall_WallSlide_Enter_NotJumpable	221
#define C_Bhv_PickUpSmall_WallSlide_Jump	222
#define C_Bhv_PickUpSmall_WallSlide_MH	223
#define C_Bhv_pikUpSmall_Grind_Dash	224
#define C_Bhv_PlasmaBall_Enter	225
#define C_Bhv_PlasmaBall_Exit	226
#define C_Bhv_PlasmaBall_MH	227
#define C_Bhv_PlayRoom_LavaLampButton	228
#define C_Bhv_PlayRoom_MageCombat_Attack_Var1	229
#define C_Bhv_PlayRoom_MageCombat_Attack_Var1_2	230
#define C_Bhv_PlayRoom_MageCombat_Attack_Var1_3	231
#define C_Bhv_PlayRoom_MageCombat_Attack_Var2	232
#define C_Bhv_PlayRoom_MageCombat_Attack_Var2_2	233
#define C_Bhv_PlayRoom_MageCombat_Attack_Var2_3	234
#define C_Bhv_PlayRoom_MageCombat_Attack_Var3	235
#define C_Bhv_PlayRoom_MageCombat_Attack_Var3_2	236
#define C_Bhv_PlayRoom_MageCombat_Attack_Var3_3	237
#define C_Bhv_PlayRoom_MageCombat_Attack_Var3_4	238
#define C_Bhv_PlayRoom_MageCombat_BeamAttack	239
#define C_Bhv_PlayRoom_MageCombat_Blink_Exit	240
#define C_Bhv_PlayRoom_MageCombat_MH	241
#define C_Bhv_PlayRoom_MageCombat_OrbAttack	242
#define C_Bhv_PlayRoom_MageCombat_TakeDamage_Var1	243
#define C_Bhv_PlayRoom_MageCombat_TakeDamage_Var2	244
#define C_Bhv_PlayRoom_MageCombat_TakeDamage_Var3	245
#define C_Bhv_PlayRoom_SpinningSpaceLamp	246
#define C_Bhv_PlayRoom_ZeroGravity_AdditiveRotation_Fwd	247
#define C_Bhv_PlayRoom_ZeroGravity_AdditiveRotation_Right	248
#define C_Bhv_PlayRoom_ZeroGravity_Back	249
#define C_Bhv_PlayRoom_ZeroGravity_Fwd	250
#define C_Bhv_PlayRoom_ZeroGravity_Left	251
#define C_Bhv_PlayRoom_ZeroGravity_MH	252
#define C_Bhv_PlayRoom_ZeroGravity_Right	253
#define C_Bhv_Pull	254
#define C_Bhv_Push_Battery_Bck	255
#define C_Bhv_Push_Battery_Fwd	256
#define C_Bhv_Push_Battery_MH	257
#define C_Bhv_Push_Enter	258
#define C_Bhv_Push_Exit	259
#define C_Bhv_Push_Fwd	260
#define C_Bhv_Push_MH	261
#define C_Bhv_Push_Struggle	262
#define C_Bhv_PushButton_Var1	263
#define C_Bhv_PushButton_Var2	264
#define C_Bhv_PushButton_Var2_SapGun	265
#define C_Bhv_PutDown	266
#define C_Bhv_PutDown_InPlace	267
#define C_Bhv_RocketFirework	268
#define C_Bhv_Shed_VacuumLaunch_Enter	269
#define C_Bhv_Shed_VacuumLaunch_MH	270
#define C_Bhv_Skydive_Bwd	271
#define C_Bhv_Skydive_Fwd	272
#define C_Bhv_Skydive_Left	273
#define C_Bhv_Skydive_MH	274
#define C_Bhv_Skydive_Right	275
#define C_Bhv_Skydive_Start	276
#define C_Bhv_Swinging_Bck	277
#define C_Bhv_Swinging_Bck_Bck	278
#define C_Bhv_Swinging_Bck_Fwd	279
#define C_Bhv_Swinging_Bck_Left	280
#define C_Bhv_Swinging_Bck_Neutral	281
#define C_Bhv_Swinging_Bck_Right	282
#define C_Bhv_Swinging_Bck_TurnAround	283
#define C_Bhv_Swinging_Enter	284
#define C_Bhv_Swinging_ExitBck	285
#define C_Bhv_Swinging_ExitFwd	286
#define C_Bhv_Swinging_Fwd	287
#define C_Bhv_Swinging_JumpBck	288
#define C_Bhv_Swinging_JumpFwd	289
#define C_Bhv_Swinging_Left	290
#define C_Bhv_Swinging_Neutral	291
#define C_Bhv_Swinging_Right	292
#define C_Bhv_Swinging_TurnAround	293
#define C_Bhv_Valve_Rotate_MH	294
#define C_Bhv_Valve_Rotate_R	295
#define C_Bhv_Valve_Rotate_R_Short	296
#define C_Bhv_Valve_StruggleLeft	297
#define C_Bhv_Valve_StruggleLeft_MH	298
#define C_Bhv_Valve_StruggleLeftEnter	299
#define C_Bhv_Valve_StruggleRight	300
#define C_Bhv_Valve_StruggleRight_MH	301
#define C_Bhv_Valve_StruggleRightEnter	302
#define C_ChangeSize_Jump_Falling	303
#define C_ChangeSize_Jump_Large_Land	304
#define C_ChangeSize_Jump_Large_Land_Jog	305
#define C_ChangeSize_Jump_Start	306
#define C_ChangeSize_Roll_Start	307
#define C_ChangeSize_Walk_Large_Bank_Left	308
#define C_ChangeSize_Walk_Large_Bank_Right	309
#define C_ChangeSize_Walk_Large_Fwd	310
#define C_ChangeSize_Walk_Large_Start	311
#define C_ChangeSize_Walk_Large_Stop	312
#define C_Crouch_Enter_GroundPound	313
#define C_Crouch_Enter_Landing	314
#define C_Crouch_Enter_MH	315
#define C_Crouch_Enter_Slide	316
#define C_Crouch_Enter_SlideMovement	317
#define C_Crouch_Enter_Walk	318
#define C_Crouch_Exit_MH	319
#define C_Crouch_Exit_Movement	320
#define C_Crouch_Exit_Movement_Walk	321
#define C_Crouch_Fwd	322
#define C_Crouch_MH	323
#define C_Crouch_Start	324
#define C_Crouch_Stop	325
#define C_CutScene_BossFight_BeamOut	326
#define C_CutScene_BossFight_Eject	327
#define C_CutScene_BossFight_EnterUFO	328
#define C_CutScene_BossFight_Intro	329
#define C_CutScene_BossFight_LandInsideUFO	330
#define C_CutScene_BossFight_LaserRippedOff	331
#define C_CutScene_BossFight_Outro	332
#define C_CutScene_Hub_SecondGenerator	333
#define C_DoubleJump	334
#define C_Exhausted_MH	335
#define C_Exhausted_MH_To_Idle	336
#define C_Grind_Btn_Press	337
#define C_Grind_Btn_Ready	338
#define C_Grind_Dash	339
#define C_Grind_Fast_MH	340
#define C_Grind_Fast_MH_Left	341
#define C_Grind_Fast_MH_Right	342
#define C_Grind_Grapple_Enter	343
#define C_Grind_Grapple_ToGrind	344
#define C_Grind_Jump	345
#define C_Grind_Land	346
#define C_Grind_Slow_MH	347
#define C_Grind_Slow_MH_Left	348
#define C_Grind_Slow_MH_LookLeft	349
#define C_Grind_Slow_MH_LookRight	350
#define C_Grind_Slow_MH_ReachLeft	351
#define C_Grind_Slow_MH_ReachLeftDown	352
#define C_Grind_Slow_MH_ReachLeftUp	353
#define C_Grind_Slow_MH_ReachRight	354
#define C_Grind_Slow_MH_ReachRightDown	355
#define C_Grind_Slow_MH_ReachRightUp	356
#define C_Grind_Slow_MH_Right	357
#define C_Grind_Transfer_LandLeft	358
#define C_Grind_Transfer_LandRight	359
#define C_Grind_Transfer_Left	360
#define C_Grind_Transfer_Right	361
#define C_Grind_TurnAround_Boost	362
#define C_Grind_TurnAround_SlowDown	363
#define C_Grind_UpsideDown_Enter	364
#define C_Grind_UpsideDown_Exit	365
#define C_Grind_UpsideDown_Fast_MH	366
#define C_Grind_UpsideDown_Fast_MH_Left	367
#define C_Grind_UpsideDown_Fast_MH_Right	368
#define C_Grind_UpsideDown_Slow_MH	369
#define C_Grind_UpsideDown_Slow_MH_LEFT	370
#define C_Grind_UpsideDown_Slow_MH_RIGHT	371
#define C_Idle_To_Action	372
#define C_Idle_To_Exhausted	373
#define C_Jog	374
#define C_Jog_Action_MH_Start_Fwd	375
#define C_Jog_Bank_Left	376
#define C_Jog_Bank_Right	377
#define C_Jog_Exhausted_MH_Start_Fwd	378
#define C_Jog_GoToStop	379
#define C_Jog_LookBackL	380
#define C_Jog_LookBackR	381
#define C_Jog_Start_Fwd	382
#define C_Jog_Start_Fwd_Left_180	383
#define C_Jog_Start_Fwd_Right_180	384
#define C_Jog_Start_InMotion	385
#define C_Jog_Start_InMotion_Var2	386
#define C_Jog_Stop_Fwd	387
#define C_Jog_Stop_Fwd_Action	388
#define C_Jog_Stop_Fwd_Easy	389
#define C_Jog_Stop_Fwd_Exhausted	390
#define C_Jog_Strafe_Bwd	391
#define C_Jog_Strafe_Fwd	392
#define C_Jog_Strafe_Left	393
#define C_Jog_Strafe_Right	394
#define C_Jump_180L	395
#define C_Jump_180R	396
#define C_Jump_Falling	397
#define C_Jump_Falling_Backwards	398
#define C_Jump_Falling_Boosted	399
#define C_Jump_Falling_Boosted_Left	400
#define C_Jump_Falling_Boosted_Right	401
#define C_Jump_Falling_Boosted_Sucked	402
#define C_Jump_Falling_Forwards	403
#define C_Jump_Falling_Left	404
#define C_Jump_Falling_Right	405
#define C_Jump_FromDash	406
#define C_Jump_FromDashStop	407
#define C_Jump_Land	408
#define C_Jump_Land_Dash	409
#define C_Jump_Land_Dash_Jog	410
#define C_Jump_Land_Dash_Walk	411
#define C_Jump_Land_High	412
#define C_Jump_Land_High_Jog	413
#define C_Jump_Land_High_Jog_Cancel	414
#define C_Jump_Land_High_Jog_Jump	415
#define C_Jump_Land_High_Start_Still	416
#define C_Jump_Land_High_Start_Still_Walk	417
#define C_Jump_Land_High_Walk	418
#define C_Jump_Land_Jog	419
#define C_Jump_Land_Jog_Jump	420
#define C_Jump_Land_Jog_Jump_Var2	421
#define C_Jump_Land_Jog_Jump_Var3	422
#define C_Jump_Land_Jog_Jump_Var4	423
#define C_Jump_Land_Jog_Jump_Var5	424
#define C_Jump_Land_Jog_Jump_Var6	425
#define C_Jump_Land_PerfectDash	426
#define C_Jump_Land_PerfectDash_Jog	427
#define C_Jump_Land_PerfectDash_Walk	428
#define C_Jump_Land_Start_Still	429
#define C_Jump_Land_Start_Still_Walk	430
#define C_Jump_Land_Still_Jump	431
#define C_Jump_Land_Walk	432
#define C_Jump_LongJump	433
#define C_Jump_LongJump_PickUpSmall	434
#define C_Jump_LongJump_Var1	435
#define C_Jump_Start	436
#define C_Jump_WallClimb	437
#define C_Jump_WallClimb_SlideDown	438
#define C_JumpFromPerfectDash	439
#define C_JumpFromPerfectDashStop	440
#define C_LedgeGrab_ClimbLeft	441
#define C_LedgeGrab_ClimbRight	442
#define C_LedgeGrab_ClimbUp	443
#define C_LedgeGrab_Drop	444
#define C_LedgeGrab_JumpBack_Left	445
#define C_LedgeGrab_JumpBack_Right	446
#define C_LedgeGrab_JumpUp	447
#define C_LedgeGrab_MH	448
#define C_LedgeGrab_MH_Left120	449
#define C_LedgeGrab_MH_Left180	450
#define C_LedgeGrab_MH_Left30	451
#define C_LedgeGrab_MH_Left60	452
#define C_LedgeGrab_MH_Left90	453
#define C_LedgeGrab_MH_Right120	454
#define C_LedgeGrab_MH_Right180	455
#define C_LedgeGrab_MH_Right30	456
#define C_LedgeGrab_MH_Right60	457
#define C_LedgeGrab_MH_Right90	458
#define C_LedgeGrab_Start	459
#define C_LedgeVault	460
#define C_LedgeVaultStart	461
#define C_MH	462
#define C_PickUpSmall_Bhv_GroundPound_Land_Exit	463
#define C_PlasmaBall_Bwd	464
#define C_PlasmaBall_Bwd_Left	465
#define C_PlasmaBall_Bwd_Right	466
#define C_PlasmaBall_Fwd	467
#define C_PlasmaBall_Fwd_Left	468
#define C_PlasmaBall_Fwd_Right	469
#define C_PlasmaBall_Left	470
#define C_PlasmaBall_Right	471
#define C_PlayRoom_MageCombat_Jog	472
#define C_PlayRoom_MageCombat_Jog_Start_Fwd	473
#define C_PlayRoom_MageCombat_jog_Stop_Fwd	474
#define C_Roll_From_GroundPound	475
#define C_Roll_From_PerfectJump	476
#define C_Roll_Jog_From_PerfectDash	477
#define C_Roll_Jump	478
#define C_Roll_PerfectDash	479
#define C_Roll_PerfectJump	480
#define C_Roll_Start	481
#define C_Roll_Stop	482
#define C_Roll_Stop_From_PerfectDash	483
#define C_Roll_To_Jog	484
#define C_Roll_To_Walk	485
#define C_Roll_Walk_From_PerfectDash	486
#define C_SkyDiveLanding	487
#define C_SkyDiveLanding_Fwd	488
#define C_SkyDiveLanding_Walk	489
#define C_Slide_Enter	490
#define C_Slide_Enter_Dash	491
#define C_Slide_Enter_Falling	492
#define C_Slide_Enter_GroundPound	493
#define C_Slide_Exit_Falling	494
#define C_Slide_ExitToMovement	495
#define C_Slide_ExitToMovement_Walk	496
#define C_Slide_Fwd	497
#define C_Slide_Jump	498
#define C_Slide_Left	499
#define C_Slide_Right	500
#define C_Sprint	501
#define C_Sprint_Jump	502
#define C_Sprint_Left	503
#define C_Sprint_Right	504
#define C_Sprint_Start_FromDash	505
#define C_SprintTurnAround	506
#define C_Strafe_Bwd	507
#define C_Strafe_BwdL	508
#define C_Strafe_BwdR	509
#define C_Strafe_Fwd	510
#define C_Strafe_FwdL	511
#define C_Strafe_FwdR	512
#define C_Strafe_Left	513
#define C_Strafe_MH	514
#define C_Strafe_Right	515
#define C_Strafe_TurnInPlace_Left	516
#define C_Strafe_TurnInPlace_Right	517
#define C_Walk_Action_MH_Start_Fwd	518
#define C_Walk_Bank_Left	519
#define C_Walk_Bank_Right	520
#define C_Walk_Exhausted_MH_Start_Fwd	521
#define C_Walk_Fwd	522
#define C_Walk_Locomotion_Walk	523
#define C_Walk_Start_Fwd	524
#define C_Walk_Start_Fwd_Left_180	525
#define C_Walk_Start_Fwd_Right_180	526
#define C_Walk_Start_InMotion	527
#define C_Walk_Start_InMotion_Var2	528
#define C_WallRun_Left_Enter	529
#define C_WallRun_Left_Jump	530
#define C_WallRun_Left_Run	531
#define C_WallRun_Right_Enter	532
#define C_WallRun_Right_Jump	533
#define C_WallRun_Right_Run	534
#define C_WallSlide_Enter	535
#define C_WallSlide_Enter_FromDash	536
#define C_WallSlide_Enter_NotJumpable	537
#define C_WallSlide_Jump	538
#define C_WallSlide_Jump_Vertical	539
#define C_WallSlide_MH	540
#define C_WallSlide_MH_ReadyToDash	541

#pragma endregion

#pragma region May_Animation

#define M_ActionMH	0
#define M_ActionMH_To_Idle	1
#define M_AirDash_Start	2
#define M_ArcadeScreenLever_Bck	3
#define M_ArcadeScreenLever_BckLeft	4
#define M_ArcadeScreenLever_BckRight	5
#define M_ArcadeScreenLever_Fwd	6
#define M_ArcadeScreenLever_FwdLeft	7
#define M_ArcadeScreenLever_FwdRight	8
#define M_ArcadeScreenLever_Left	9
#define M_ArcadeScreenLever_MH	10
#define M_ArcadeScreenLever_Right	11
#define M_ArcadeScreenLever_Trigger	12
#define M_Bounce1	13
#define M_Bounce2	14
#define M_Bounce3	15
#define M_Bounce4	16
#define M_BruteCombat_Attack_Var1	17
#define M_BruteCombat_Attack_Var2	18
#define M_BruteCombat_Attack_Var3	19
#define M_BruteCombat_Dash	20
#define M_BruteCombat_GroundSmash	21
#define M_BruteCombat_Jog	22
#define M_BruteCombat_MH	23
#define M_BruteCombat_Start_Fwd	24
#define M_BruteCombat_Stop	25
#define M_BruteCombat_TakeDamage_Heavy_Var1	26
#define M_BruteCombat_TakeDamage_Heavy_Var2	27
#define M_BruteCombat_TakeDamage_Heavy_Var3	28
#define M_BruteCombat_UltimatWhirlwind_MH	29
#define M_BruteCombat_WhirlWind_MH	30
#define M_Bump_Collide	31
#define M_Bump_Collide_Fall	32
#define M_ChessMiniGame_Gestures_Point_Var1	33
#define M_Controllable_Right	34
#define M_Crouch_Enter_GroundPound	35
#define M_Crouch_Enter_Landing	36
#define M_Crouch_Enter_MH	37
#define M_Crouch_Enter_Movement	38
#define M_Crouch_Enter_Slide	39
#define M_Crouch_Enter_Slide_Movement	40
#define M_Crouch_Exit_MH	41
#define M_Crouch_Exit_Movement	42
#define M_Crouch_Exit_Movement_Slow	43
#define M_Crouch_MH	44
#define M_Crouch_Walk	45
#define M_Crouch_Walk_Start	46
#define M_Crouch_Walk_Stop	47
#define M_CutScene_BeamUp_Intro_May	48
#define M_CutScene_SpaceStation_BossFight_BeamOut	49
#define M_CutScene_SpaceStation_BossFight_Eject	50
#define M_DashMoveTo_Start	51
#define M_DashMoveTo_Start_InAir	52
#define M_DashMoveTo_Start_Left90	53
#define M_DashMoveTo_Start_Right90	54
#define M_Death_Fall_MH	55
#define M_Death_Oil_Drown	56
#define M_DoubleJump	57
#define M_ExhaustedMH	58
#define M_ExhaustedMH_To_Idle	59
#define M_FidgetSpinner_Enter	60
#define M_FidgetSpinner_Exit	61
#define M_FidgetSpinner_Hover_Fast_MH	62
#define M_FidgetSpinner_Hover_Fast_MH_Left	63
#define M_FidgetSpinner_Hover_Fast_MH_Right	64
#define M_FidgetSpinner_Hover_Slow_MH	65
#define M_FidgetSpinner_Hover_Slow_MH_Left	66
#define M_FidgetSpinner_Hover_Slow_MH_Right	67
#define M_FidgetSpinner_InAir_Enter	68
#define M_FidgetSpinner_InAir_Exit	69
#define M_Grind_Btn_Press	70
#define M_Grind_Btn_Ready	71
#define M_Grind_Dash	72
#define M_Grind_Fast_MH	73
#define M_Grind_Fast_MH_Left	74
#define M_Grind_Fast_MH_LookLeft	75
#define M_Grind_Fast_MH_LookRight	76
#define M_Grind_Fast_MH_Right	77
#define M_Grind_Grapple_Enter	78
#define M_Grind_Grapple_ToGrind	79
#define M_Grind_Jump	80
#define M_Grind_Land	81
#define M_Grind_Slow_MH	82
#define M_Grind_Slow_MH_Left	83
#define M_Grind_Slow_MH_LookLeft	84
#define M_Grind_Slow_MH_LookRight	85
#define M_Grind_Slow_MH_ReachLeft	86
#define M_Grind_Slow_MH_ReachLeftDown	87
#define M_Grind_Slow_MH_ReachLeftUp	88
#define M_Grind_Slow_MH_ReachRight	89
#define M_Grind_Slow_MH_ReachRightDown	90
#define M_Grind_Slow_MH_ReachRightUp	91
#define M_Grind_Slow_MH_Right	92
#define M_Grind_Transfer_LandLeft	93
#define M_Grind_Transfer_LandRight	94
#define M_Grind_Transfer_Left	95
#define M_Grind_Transfer_Right	96
#define M_Grind_TurnAround_Boost	97
#define M_Grind_TurnAround_SlowDown	98
#define M_Grind_UpsideDown_Enter	99
#define M_Grind_UpsideDown_Exit	100
#define M_Grind_UpsideDown_Fast_Left	101
#define M_Grind_UpsideDown_Fast_MH	102
#define M_Grind_UpsideDown_Fast_Right	103
#define M_Grind_UpsideDown_Slow_Left	104
#define M_Grind_UpsideDown_Slow_MH	105
#define M_Grind_UpsideDown_Slow_Right	106
#define M_GroundPound_Falling	107
#define M_GroundPound_Jump_High	108
#define M_GroundPound_Jump_Low	109
#define M_GroundPound_Land	110
#define M_GroundPound_Land_Exit	111
#define M_GroundPound_Land_MH	112
#define M_GroundPound_Start	113
#define M_HoldButton_Enter	114
#define M_HoldButton_Exit	115
#define M_HoldButton_MH	116
#define M_Jog	117
#define M_Jog_Action_Start	118
#define M_Jog_Bank_Left	119
#define M_Jog_Bank_Right	120
#define M_Jog_Exhausted_Start	121
#define M_Jog_LookBackL	122
#define M_Jog_LookBackR	123
#define M_Jog_Start	124
#define M_Jog_Start_InMotion	125
#define M_Jog_Start_InMotion_Var2	126
#define M_Jog_Stop	127
#define M_Jog_Stop_Action	128
#define M_Jog_Stop_Easy	129
#define M_Jog_Stop_Exhausted	130
#define M_Jog_Turn_Left180	131
#define M_Jog_Turn_Right180	132
#define M_Jump_180L	133
#define M_Jump_180R	134
#define M_Jump_Falling	135
#define M_Jump_Falling_Bck	136
#define M_Jump_Falling_Boosted	137
#define M_Jump_Falling_Boosted_Left	138
#define M_Jump_Falling_Boosted_Right	139
#define M_Jump_Falling_Boosted_Sucked	140
#define M_Jump_Falling_Fwd	141
#define M_Jump_Falling_Left	142
#define M_Jump_Falling_right	143
#define M_Jump_FromDash	144
#define M_Jump_FromDashStop	145
#define M_Jump_FromPerfectDash	146
#define M_Jump_FromPerfectDashStop	147
#define M_Jump_Land	148
#define M_Jump_Land_Dash	149
#define M_Jump_Land_Dash_Jog	150
#define M_Jump_Land_Dash_Walk	151
#define M_Jump_Land_High	152
#define M_Jump_Land_High_Jog	153
#define M_Jump_Land_High_Walk	154
#define M_Jump_Land_Jog	155
#define M_Jump_Land_Jog_Jump	156
#define M_Jump_Land_Jog_Jump_Var2	157
#define M_Jump_Land_Jog_Jump_Var3	158
#define M_Jump_Land_PerfectDash	159
#define M_Jump_Land_PerfectDash_Jog	160
#define M_Jump_Land_PerfectDash_Walk	161
#define M_Jump_Land_Walk	162
#define M_Jump_LongJump	163
#define M_Jump_LongJump_PickUpSmall	164
#define M_Jump_Start	165
#define M_Jump_Start_Fwd	166
#define M_KnockDown_Back_Land	167
#define M_KnockDown_Back_MH	168
#define M_KnockDown_Back_Start	169
#define M_KnockDown_Front	170
#define M_KnockDown_Front_Land	171
#define M_KnockDown_Front_MH	172
#define M_KnockDown_Front_Start	173
#define M_KnockDown_Left_Land	174
#define M_KnockDown_Left_MH	175
#define M_KnockDown_Left_Start	176
#define M_KnockDown_Right_Land	177
#define M_KnockDown_Right_MH	178
#define M_KnockDown_Right_Start	179
#define M_LavaLampButton	180
#define M_LedgeGrab_ClimbUp	181
#define M_LedgeGrab_JumpBack_Left	182
#define M_LedgeGrab_JumpBack_Right	183
#define M_LedgeGrab_JumpUp	184
#define M_LedgeGrab_MH	185
#define M_LedgeGrab_MH_Left120	186
#define M_LedgeGrab_MH_Left180	187
#define M_LedgeGrab_MH_Left30	188
#define M_LedgeGrab_MH_Left60	189
#define M_LedgeGrab_MH_Left90	190
#define M_LedgeGrab_MH_Right120	191
#define M_LedgeGrab_MH_Right180	192
#define M_LedgeGrab_MH_Right30	193
#define M_LedgeGrab_MH_Right60	194
#define M_LedgeGrab_MH_Right90	195
#define M_LedgeGrab_Start	196
#define M_LedgeVault	197
#define M_LedgeVaultStart	198
#define M_Lever_Left	199
#define M_Lever_Right	200
#define M_LeverPull_Exit_Fast	201
#define M_LeverPull_Exit_Slow	202
#define M_LeverPull_MH	203
#define M_LeverPull_Start_Fast	204
#define M_MH	205
#define M_MH_Gesture_Big_Waiting_Enter	206
#define M_MH_Gesture_Big_Waiting_MH	207
#define M_MH_Gesture_Small_BrushOffDir	208
#define M_MH_Gesture_Small_InspectNamils	209
#define M_MH_Gesture_Small_Knock	210
#define M_MH_Gesture_Small_LookAround	211
#define M_MH_Gesture_Small_Stretch	212
#define M_MH_Gesture_Small_Watch	213
#define M_MH_To_Action	214
#define M_MH_To_Exhausted	215
#define M_MiniGame_Emotes_Applause	216
#define M_MiniGame_Emotes_Boxing	217
#define M_MiniGame_Emotes_Dance_Var1	218
#define M_MiniGame_Emotes_FlimsyDance	219
#define M_MIniGame_Emotes_FrontFlip	220
#define M_MiniGame_Emotes_Giggle	221
#define M_MiniGame_Emotes_Gunslinger	222
#define M_MIniGame_Emotes_Italian	223
#define M_MiniGame_Emotes_Lose_Var1	224
#define M_MiniGame_Emotes_Lose_Var2	225
#define M_MiniGame_Emotes_Lose_Var3	226
#define M_MIniGame_Emotes_Macarena	227
#define M_MiniGame_Emotes_ShoulderBrush	228
#define M_PickUp	229
#define M_PickUp_Aim_Strafe_Bwd	230
#define M_PickUp_Aim_Strafe_Fwd	231
#define M_PickUp_Aim_Strafe_Left	232
#define M_PickUp_Aim_Strafe_Right	233
#define M_PickUp_AimSpace_Center	234
#define M_PickUp_AimSpace_Down_BS	235
#define M_PickUp_AimSpace_Up_BS	236
#define M_PickUp_FuseCrab_PutInSocket	237
#define M_PickUp_Jog	238
#define M_PickUp_Jog_Stop	239
#define M_PickUp_Jump_Falling	240
#define M_PickUp_Jump_Land	241
#define M_PickUp_Jump_Land_Jog	242
#define M_PickUp_Jump_Start	243
#define M_PickUp_MH	244
#define M_PickUp_Throw	245
#define M_PickUpHeavySmall	246
#define M_PickUpHeavySmall_Jog	247
#define M_PickUpHeavySmall_Jog_Start	248
#define M_PickUpHeavySmall_Jog_Start_InMotion	249
#define M_PickUpHeavySmall_Jog_Stop	250
#define M_PickUpHeavySmall_Jump_Falling	251
#define M_PickUpHeavySmall_Jump_Land	252
#define M_PickUpHeavySmall_Jump_Land_Jog	253
#define M_PickUpHeavySmall_Jump_Start	254
#define M_PickUpHeavySmall_MH	255
#define M_PickUpHeavySmall_PutDown	256
#define M_PickUpHeavySmall_PutDown_InPlace	257
#define M_PickUpSamll_GroundPound_Land_MH	258
#define M_PickUpSamll_Swinging_Exit_Bck_Left	259
#define M_PickUpSmall	260
#define M_PickUpSmall_Aim_MH	261
#define M_PickUpSmall_Aim_Strafe_Bwd	262
#define M_PickUpSmall_Aim_Strafe_Fwd	263
#define M_PickUpSmall_Aim_Strafe_Left	264
#define M_PickUpSmall_Aim_Strafe_Right	265
#define M_PickUpSmall_AimSpace_Center	266
#define M_PickUpSmall_AimSpace_Down	267
#define M_PickUpSmall_AimSpace_Up	268
#define M_PickUpSmall_AirDash_Start	269
#define M_PickUpSmall_Bounce1	270
#define M_PickUpSmall_Bounce2	271
#define M_PickUpSmall_Bounce3	272
#define M_PickUpSmall_Bounce4	273
#define M_PickUpSmall_Grind_Dash	274
#define M_PickUpSmall_Grind_Fast_MH	275
#define M_PickUpSmall_Grind_Grapple_Enter	276
#define M_PickUpSmall_Grind_Grapple_ToGrind	277
#define M_PickUpSmall_Grind_Jump	278
#define M_PickUpSmall_Grind_Land	279
#define M_PickUpSmall_Grind_Slow_MH	280
#define M_PickUpSmall_Grind_Transfer_LandLeft	281
#define M_PickUpSmall_Grind_Transfer_LandRight	282
#define M_PickUpSmall_Grind_Transfer_Left	283
#define M_PickUpSmall_Grind_Transfer_Right	284
#define M_PickUpSmall_Grind_TurnAround_Boost	285
#define M_PickUpSmall_Grind_TurnAround_SlowDown	286
#define M_PickUpSmall_GroundPound_Falling	287
#define M_PickUpSmall_GroundPound_Jump_High	288
#define M_PickUpSmall_GroundPound_Jump_Low	289
#define M_PickUpSmall_GroundPound_Land_Exit	290
#define M_PickUpSmall_GroundPound_Start	291
#define M_PickUpSmall_Jog	292
#define M_PickUpSmall_Jog_Start	293
#define M_PickUpSmall_Jog_Start_InMotion	294
#define M_PickUpSmall_Jog_Stop	295
#define M_PickUpSmall_Jump_Falling	296
#define M_PickUpSmall_Jump_Land	297
#define M_PickUpSmall_Jump_Land_High	298
#define M_PickUpSmall_Jump_Land_Jog	299
#define M_PickUpSmall_Jump_Start	300
#define M_PickUpSmall_LedgeGrab_ClimbUp	301
#define M_PickUpSmall_LedgeGrab_JumpBack_Left	302
#define M_PickUpSmall_LedgeGrab_jumpUp	303
#define M_PickUpSmall_LedgeGrab_MH	304
#define M_PickUpSmall_LedgeGrab_MH_Left120	305
#define M_PickUpSmall_LedgeGrab_MH_Left180	306
#define M_PickUpSmall_LedgeGrab_MH_Left30	307
#define M_PickUpSmall_LedgeGrab_MH_Left60	308
#define M_PickUpSmall_LedgeGrab_MH_Left90	309
#define M_PickUpSmall_LedgeGrab_Start	310
#define M_PickUpSmall_LedgeVault	311
#define M_PickUpSmall_LedgeVaultStart	312
#define M_PickUpSmall_MH	313
#define M_PickUpSmall_PutDown	314
#define M_PickUpSmall_PutDown_InPlace	315
#define M_PickUpSmall_Roll_Jog_From_PerfectDash	316
#define M_PickUpSmall_Roll_PerfectDash	317
#define M_PickUpSmall_Roll_Start	318
#define M_PickUpSmall_Roll_Stop	319
#define M_PickUpSmall_Roll_Stop_From_PerfectDash	320
#define M_PickUpSmall_Roll_To_Jog	321
#define M_PickUpSmall_Sprint	322
#define M_PickUpSmall_Sprint_Left	323
#define M_PickUpSmall_Sprint_Right	324
#define M_PickUpSmall_Sprint_Start_FromDash	325
#define M_PickUpSmall_SprintTurnAround	326
#define M_PickUpSmall_Swinging_ApexTurn_Bck_Left	327
#define M_PickUpSmall_Swinging_ApexTurn_Bck_Right	328
#define M_PickUpSmall_Swinging_ApexTurn_Left	329
#define M_PickUpSmall_Swinging_ApexTurn_Right	330
#define M_PickUpSmall_Swinging_Bck_Fwd	331
#define M_PickUpSmall_Swinging_Bck_Left	332
#define M_PickUpSmall_Swinging_Bck_Right	333
#define M_PickUpSmall_Swinging_Enter	334
#define M_PickUpSmall_SwingIng_Enter_Left	335
#define M_PickUpSmall_Swinging_Enter_Right	336
#define M_PickUpSmall_Swinging_Exit_Bck_Right	337
#define M_PickUpSmall_Swinging_Exit_Fwd	338
#define M_PickUpSmall_Swinging_Fwd	339
#define M_PickUpSmall_Swinging_Left	340
#define M_PickUpSmall_Swinging_Right	341
#define M_PickUpSmall_Throw	342
#define M_PickUpSmall_WallSlide_Enter	343
#define M_PickUpSmall_WallSlide_Enter_FromDash	344
#define M_PickUpSmall_WallSlide_Enter_NotJumpable	345
#define M_PickUpSmall_WallSlide_Jump	346
#define M_PickUpSmall_WallSlide_MH	347
#define M_PinBall_Enter	348
#define M_PinBall_Exit	349
#define M_PinBall_HitLeft	350
#define M_PinBall_HitRight	351
#define M_PinBall_Left	352
#define M_PinBall_Left_Hit	353
#define M_PinBall_Left_HitStart	354
#define M_PinBall_MH	355
#define M_PinBall_MH_Hit	356
#define M_PinBall_MH_HitStart	357
#define M_PinBall_Right	358
#define M_PinBall_Right_Hit	359
#define M_PinBall_Right_HitStart	360
#define M_PlasmaCube_Bwd	361
#define M_PlasmaCube_Bwd_Left	362
#define M_PlasmaCube_Bwd_Right	363
#define M_PlasmaCube_Bwd_Struggle	364
#define M_PlasmaCube_BwdLeft_Struggle	365
#define M_PlasmaCube_BwdRight_Struggle	366
#define M_PlasmaCube_Enter	367
#define M_PlasmaCube_Exit	368
#define M_PlasmaCube_Fall_Enter	369
#define M_PlasmaCube_Fall_Exit	370
#define M_PlasmaCube_Fall_MH	371
#define M_PlasmaCube_Fwd	372
#define M_PlasmaCube_Fwd_Left	373
#define M_PlasmaCube_Fwd_Right	374
#define M_PlasmaCube_Fwd_Struggle	375
#define M_PlasmaCube_FwdLeft_Struggle	376
#define M_PlasmaCube_FwdRight_Struggle	377
#define M_PlasmaCube_Left	378
#define M_PlasmaCube_Left_Struggle	379
#define M_PlasmaCube_MH	380
#define M_PlasmaCube_Right	381
#define M_PlasmaCube_Right_Struggle	382
#define M_Pull	383
#define M_Push_Enter	384
#define M_Push_Exit	385
#define M_Push_Fwd	386
#define M_Push_MH	387
#define M_Push_Struggle	388
#define M_PushButton_Var1	389
#define M_PushButton_Var2	390
#define M_PushButton_Var2_Mirror	391
#define M_PushButton_Var2_Sniper	392
#define M_PutDown	393
#define M_PutDown_InPlace	394
#define M_Rocket_Down	395
#define M_Rocket_Enter	396
#define M_Rocket_Exit	397
#define M_Rocket_Left	398
#define M_Rocket_MH	399
#define M_Rocket_Right	400
#define M_Rocket_Up	401
#define M_RocketFirework	402
#define M_Roll_From_GroundPound	403
#define M_Roll_From_PerfectJump	404
#define M_Roll_Jog	405
#define M_Roll_Jog_From_PerfectDash	406
#define M_Roll_PerfectDash	407
#define M_Roll_PerfectJump	408
#define M_Roll_Start	409
#define M_Roll_Stop	410
#define M_Roll_Stop_From_PerfectDash	411
#define M_Roll_Walk	412
#define M_Roll_Walk_From_PerfectDash	413
#define M_Skydive_Falling	414
#define M_Skydive_Falling_Bck	415
#define M_Skydive_Falling_Fwd	416
#define M_Skydive_Falling_Left	417
#define M_Skydive_Falling_Right	418
#define M_Skydive_Start	419
#define M_SkyDiveLanding	420
#define M_SkyDiveLanding_Fwd	421
#define M_SkyDiveLanding_Walk	422
#define M_Slide_Enter	423
#define M_Slide_Enter_Dash	424
#define M_Slide_Enter_Falling	425
#define M_Slide_Enter_GroundPound	426
#define M_Slide_Exit_Falling	427
#define M_Slide_ExitToMovement	428
#define M_Slide_ExitToWalk	429
#define M_Slide_Fast_Neutral	430
#define M_Slide_Jump	431
#define M_Slide_Left	432
#define M_Slide_Netural	433
#define M_Slide_Right	434
#define M_SpacePortal_Exit	435
#define M_SpacePortal_Travel_MH	436
#define M_SpaceStation_BossFight_Intro	437
#define M_SpaceStation_BossFight_LaserRippedOff	438
#define M_SpaceStation_BossFight_Outro	439
#define M_SpaceStation_Hub_SecondGenerator	440
#define M_spinningSpaceLamp	441
#define M_Sprint	442
#define M_Sprint_Left	443
#define M_Sprint_Right	444
#define M_Sprint_Start_FromDash	445
#define M_SprintTurnAround	446
#define M_Strafe_Bwd	447
#define M_Strafe_BwdL	448
#define M_Strafe_BwdR	449
#define M_Strafe_Fwd	450
#define M_Strafe_FwdL	451
#define M_Strafe_FwdR	452
#define M_Strafe_L	453
#define M_Strafe_MH	454
#define M_Strafe_R	455
#define M_Strafe_TurnInPlace_Left	456
#define M_Strafe_TurnInPlace_Right	457
#define M_Swinging_ApexTurn_Bck_Left	458
#define M_Swinging_ApexTurn_Bck_Right	459
#define M_Swinging_ApexTurn_Left	460
#define M_Swinging_ApexTurn_Right	461
#define M_Swinging_Bck	462
#define M_Swinging_Bck_Left	463
#define M_Swinging_Bck_Right	464
#define M_Swinging_Enter	465
#define M_Swinging_Enter_Left	466
#define M_Swinging_Enter_Right	467
#define M_Swinging_Exit_Bck_Left	468
#define M_Swinging_Exit_Bck_Right	469
#define M_Swinging_Exit_Down	470
#define M_Swinging_Exit_Fwd	471
#define M_Swinging_Fwd	472
#define M_Swinging_Left	473
#define M_Swinging_Right	474
#define M_Ufo_Controllable_Left	475
#define M_Ufo_Controllable_MH	476
#define M_VacuumLaunch_Enter	477
#define M_Valve_Rotate_MH	478
#define M_Valve_Rotate_R	479
#define M_Valve_Rotate_R_Short	480
#define M_Valve_StruggleLeft	481
#define M_Valve_StruggleLeft_MH	482
#define M_Valve_StruggleLeftEnter	483
#define M_Valve_StruggleRight	484
#define M_Valve_StruggleRight_MH	485
#define M_Valve_StruggleRightEnter	486
#define M_Walk_Action_Start	487
#define M_Walk_Bank_Left	488
#define M_Walk_Bank_Right	489
#define M_Walk_Exhausted_Start	490
#define M_Walk_Fwd	491
#define M_Walk_Start	492
#define M_Walk_Start_InMotion	493
#define M_Walk_Start_InMotion_Var2	494
#define M_Walk_Turn_Left180	495
#define M_Walk_Turn_Right180	496
#define M_WalkIn	497
#define M_WallClimb_Down	498
#define M_WallClimb_Left	499
#define M_WallClimb_MH	500
#define M_WallClimb_Right	501
#define M_WallClimb_Up	502
#define M_WallRun_Left_Enter	503
#define M_WallRun_Left_Jump	504
#define M_WallRun_Left_Run	505
#define M_WallRun_Right_Enter	506
#define M_WallRun_Right_Jump	507
#define M_WallRun_Right_Run	508
#define M_WallSlide_Enter	509
#define M_WallSlide_Enter_From_Dash	511
#define M_WallSlide_Enter_NotJumpable	512
#define M_WallSlide_Jump	513
#define M_WallSlide_Jump_Vertical	512
#define M_WallSlide_MH	513
#define M_WallSlide_MH_ReadyToDash	514
#define M_ZeroGravity_AdditiveRotation_Fwd	513
#define M_ZeroGravity_AdditiveRotation_Ref	514
#define M_ZeroGravity_AdditiveRotation_Right	515
#define M_ZeroGravity_Bck	514
#define M_ZeroGravity_Fwd	515
#define M_ZeroGravity_MH	516
#pragma endregion