#pragma once

/* For. Cody */
enum CODY_ANIM
{
	  DUMMY_ANIM, C_ActionMH
	, C_ActionMH_To_Idle
	, C_AirDash_Start
	, C_Bhv_ArcadeScreenLever_Bck
	, C_Bhv_ArcadeScreenLever_BckLeft
	, C_Bhv_ArcadeScreenLever_BckRight
	, C_Bhv_ArcadeScreenLever_Fwd
	, C_Bhv_ArcadeScreenLever_FwdLeft
	, C_Bhv_ArcadeScreenLever_FwdRight
	, C_Bhv_ArcadeScreenLever_Left
	, C_Bhv_ArcadeScreenLever_MH
	, C_Bhv_ArcadeScreenLever_Right
	, C_Bhv_ArcadeScreenLever_Trigger
	, C_Bhv_Bounce_01
	, C_Bhv_Bounce_02
	, C_Bhv_Bounce_03
	, C_Bhv_Bounce_04
	, C_Bhv_Bump_Collide
	, C_Bhv_Bump_Collide_Fall
	, C_Bhv_ChagneSize_PlanetPush_Small
	, C_Bhv_ChangeSize_GroundPound_Falling
	, C_Bhv_ChangeSize_GroundPound_Land_Exit
	, C_Bhv_ChangeSize_GroundPound_Land_MH
	, C_Bhv_ChangeSize_GroundPound_Start
	, C_Bhv_ChangeSize_PlanetPush_Large
	, C_Bhv_ChangeSize_PlanetPush_Medium
	, C_Bhv_ChessMiniGame_Gestures_Point
	, C_Bhv_DashMoveTo_Start
	, C_Bhv_DashMoveTo_Start_InAir
	, C_Bhv_DashMoveTo_Start_Left90
	, C_Bhv_DashMoveTo_Start_Right90
	, C_Bhv_Death_Fall_MH
	, C_Bhv_Death_Oil_Drown
	, C_Bhv_FidgetSpinner_Enter
	, C_Bhv_FidgetSpinner_Exit
	, C_Bhv_FidgetSpinner_Hover_Fast_MH
	, C_Bhv_FidgetSpinner_Hover_Fast_MH_Left
	, C_Bhv_FidgetSpinner_Hover_Fast_MH_Right
	, C_Bhv_FidgetSpinner_Hover_Slow_MH
	, C_Bhv_FidgetSpinner_Hover_Slow_MH_Left
	, C_Bhv_FidgetSpinner_Hover_Slow_MH_Right
	, C_Bhv_FidgetSpinner_InAir_Enter
	, C_Bhv_FidgetSpinner_InAir_Exit
	, C_Bhv_Generic_WalkIn
	, C_Bhv_GroundPound_Falling
	, C_Bhv_GroundPound_Jump_High
	, C_Bhv_GroundPound_Jump_Low
	, C_Bhv_GroundPound_Land
	, C_Bhv_GroundPound_Land_Exit
	, C_Bhv_GroundPound_Land_MH
	, C_Bhv_GroundPound_Start
	, C_Bhv_HoldButton_Enter
	, C_Bhv_HoldButton_Exit
	, C_Bhv_HoldButton_MH
	, C_Bhv_Jump_Start
	, C_Bhv_KnockDown_Back_Land
	, C_Bhv_KnockDown_Back_MH
	, C_Bhv_KnockDown_Back_Start
	, C_Bhv_KnockDown_Front
	, C_Bhv_KnockDown_Front_Land
	, C_Bhv_KnockDown_Front_MH
	, C_Bhv_KnockDown_Front_Start
	, C_Bhv_KnockDown_Left_Land
	, C_Bhv_KnockDown_Left_MH
	, C_Bhv_KnockDown_Left_Start
	, C_Bhv_knockDown_Right_Land
	, C_Bhv_KnockDown_Right_MH
	, C_Bhv_KnockDown_Right_Start
	, C_Bhv_Lever_Left
	, C_Bhv_Lever_Right
	, C_Bhv_LeverPull_Exit_Fast
	, C_Bhv_LeverPull_Exit_Slow
	, C_Bhv_LeverPull_MH
	, C_Bhv_LeverPull_Start_Fast
	, C_Bhv_MH_Gesture_Big_Waiting_Enter
	, C_Bhv_MH_Gesture_Big_Waiting_MH
	, C_Bhv_MH_Gesture_Small_AdjustLeaf
	, C_Bhv_MH_Gesture_Small_Belly
	, C_Bhv_MH_Gesture_Small_Drumming
	, C_Bhv_MH_Gesture_Small_InspectNails
	, C_Bhv_MH_Gesture_Small_LookAround
	, C_Bhv_MH_Gesture_Small_Scratch
	, C_Bhv_MH_Gesture_Small_Stretch
	, C_Bhv_MH_Gesture_Small_TossLeaf
	, C_Bhv_MiniGame_Emotes_AssDance
	, C_Bhv_MiniGame_Emotes_CossackDance
	, C_Bhv_MiniGame_Emotes_Explosion
	, C_Bhv_MiniGame_Emotes_FistPump
	, C_Bhv_MiniGame_Emotes_Fonzie
	, C_Bhv_MiniGame_Emotes_HappyDance
	, C_Bhv_MiniGame_Emotes_Huzzah
	, C_Bhv_MiniGame_Emotes_JumpUpLand
	, C_Bhv_MiniGame_Emotes_KarateBow
	, C_Bhv_MiniGame_Emotes_LeafFlex
	, C_Bhv_MiniGame_Emotes_Lose_Var1
	, C_Bhv_MiniGame_Emotes_Lose_Var2
	, C_Bhv_MiniGame_Emotes_Lose_Var3
	, C_Bhv_MiniGame_Emotes_ShoulderBrush
	, C_Bhv_MiniGame_Emotes_WatchingYou
	, C_Bhv_MiniGame_Emotes_WeirdRobot
	, C_Bhv_PickUp
	, C_Bhv_PickUp_Aim_Strafe_Bwd
	, C_Bhv_PickUp_Aim_Strafe_Fwd
	, C_Bhv_PickUp_Aim_Strafe_Left
	, C_Bhv_PickUp_Aim_Strafe_Right
	, C_Bhv_PickUp_AimSpace_Center
	, C_Bhv_PickUp_AimSpace_Down
	, C_Bhv_pickUp_AimSpace_Up
	, C_Bhv_PickUp_FuseCrab_PutInSocket
	, C_Bhv_PickUp_Jog
	, C_Bhv_PickUp_Jog_Stop
	, C_Bhv_PickUp_Jump_Falling
	, C_Bhv_PickUp_Jump_Land
	, C_Bhv_PickUp_Jump_Land_Jog
	, C_Bhv_PickUp_MH
	, C_Bhv_PickUp_Throw
	, C_Bhv_PickUpHeavySmall_Jog
	, C_Bhv_PickUpHeavySmall_Jog_StartInMotion
	, C_Bhv_PickUpHeavySmall_Jog_Stop
	, C_Bhv_PickUpHeavySmall_Jump_Falling
	, C_Bhv_PickUpHeavySmall_Jump_Land
	, C_Bhv_PickUpHeavySmall_Jump_Land_Jog
	, C_Bhv_PickUpHeavySmall_Jump_Start
	, C_Bhv_PickUpHeavySmall_MH
	, C_Bhv_PickUpHeavySmall_PickUp
	, C_Bhv_PickUpHeavySmall_PutDown
	, C_Bhv_PickUpHeavySmall_PutDown_InPlace
	, C_Bhv_PickUpSmall
	, C_Bhv_PickUpSmall_Aim_MH
	, C_Bhv_PickUpSmall_Aim_Strafe_Fwd
	, C_Bhv_PickUpSmall_AimSpace_Down
	, C_Bhv_PickUpSmall_AimSpace_Up
	, C_Bhv_PickUpSmall_AirDashStart
	, C_Bhv_PickUpSmall_Bhv_GroundPound_Falling
	, C_Bhv_PickUpSmall_Bhv_GroundPound_Jump_High
	, C_Bhv_PickUpSmall_Bhv_GroundPound_Jump_Low
	, C_Bhv_PickUpSmall_Bhv_GroundPound_Land
	, C_Bhv_PickUpSmall_Bhv_GroundPound_Land_MH
	, C_Bhv_PickUpSmall_Bhv_GroundPound_Start
	, C_Bhv_PickUpSmall_Bhv_Swinging_Bck
	, C_Bhv_PickUpSmall_Bhv_Swinging_Bck_Bck
	, C_Bhv_PickUpSmall_Bhv_Swinging_Bck_Fwd
	, C_Bhv_PickUpSmall_Bhv_Swinging_Bck_Neutral
	, C_Bhv_PickUpSmall_Bhv_Swinging_Bck_TurnAround
	, C_Bhv_PickUpSmall_Bhv_Swinging_ExitBck
	, C_Bhv_PickUpSmall_Bhv_Swinging_ExitFwd
	, C_Bhv_PickUpSmall_Bhv_Swinging_Fwd
	, C_Bhv_PickUpSmall_Bhv_Swinging_JumpBck
	, C_Bhv_PickUpSmall_Bhv_Swinging_JumpFwd
	, C_Bhv_PickUpSmall_Bhv_Swinging_Neutral
	, C_Bhv_PickUpSmall_Bhv_Swinging_TurnAround
	, C_Bhv_PickUpSmall_Bounce_01
	, C_Bhv_PickUpSmall_Bounce_02
	, C_Bhv_PickUpSmall_Bounce_03
	, C_Bhv_PickUpSmall_Bounce_04
	, C_Bhv_PickUpSmall_DoubleJump
	, C_Bhv_PickUpSmall_Grind_Fast
	, C_Bhv_PickUpSmall_Grind_Fast_MH_Left
	, C_Bhv_PickUpSmall_Grind_Fast_MH_Right
	, C_Bhv_PickUpSmall_Grind_Grapple_Enter
	, C_Bhv_PickUpSmall_Grind_Grapple_ToGrind
	, C_Bhv_PickUpSmall_Grind_Jump
	, C_Bhv_PickUpSmall_Grind_Land
	, C_Bhv_PickUpSmall_Grind_Slow_MH
	, C_Bhv_PickUpSmall_Grind_Slow_MH_Left
	, C_Bhv_PickUpSmall_Grind_Slow_MH_Right
	, C_Bhv_PickUpSmall_Grind_TurnAround_Boost
	, C_Bhv_PickUpSmall_Grind_TurnAround_SlowDown
	, C_Bhv_PickUpSmall_Jog
	, C_Bhv_PickUpSmall_Jog_GoToStop
	, C_Bhv_PickUpSmall_Jog_Start_Fwd
	, C_Bhv_PickUpSmall_Jog_Start_InMotion
	, C_Bhv_PickUpSmall_Jog_Stop_Fwd
	, C_Bhv_PickUpSmall_Jump_Falling
	, C_Bhv_PickUpSmall_Jump_From_Landing
	, C_Bhv_PickUpSmall_Jump_Land
	, C_Bhv_PickUpSmall_Jump_Land_Jog
	, C_Bhv_PickUpSmall_Jump_Start
	, C_Bhv_PickUpSmall_Jump_StartFromStill
	, C_Bhv_PickUpSmall_LedgeGrab_ClimbUp
	, C_Bhv_PickUpSmall_LedgeGrab_Drop
	, C_Bhv_PickUpSmall_LedgeGrab_JumpBack_Left
	, C_Bhv_PickUpSmall_LedgeGrab_JumpUp
	, C_Bhv_PickUpSmall_LedgeGrab_MH
	, C_Bhv_PickUpSmall_LedgeGrab_MH_Left120
	, C_Bhv_PickUpSmall_LedgeGrab_MH_Left180
	, C_Bhv_PickUpSmall_LedgeGrab_MH_Left30
	, C_Bhv_PickUpSmall_LedgeGrab_MH_Left60
	, C_Bhv_PickUpSmall_LedgeGrab_MH_Left90
	, C_Bhv_PickUpSmall_LedgeGrab_Start
	, C_Bhv_PickUpSmall_LedgeVault
	, C_Bhv_PickUpSmall_LedgeVaultStart
	, C_Bhv_PickUpSmall_MH
	, C_Bhv_PickUpSmall_PerfectDash
	, C_Bhv_PickUpSmall_PerfectDashJog
	, C_Bhv_PickUpSmall_PerfectDashStop
	, C_Bhv_PickUpSmall_PutDown
	, C_Bhv_PickUpSmall_PutDown_InPlace
	, C_Bhv_PickUpSmall_Roll_Start
	, C_Bhv_PickUpSmall_Roll_Stop
	, C_Bhv_PickUpSmall_Roll_To_Jog
	, C_Bhv_PickUpSmall_Sprint
	, C_Bhv_PickUpSmall_SprintStartFromDash
	, C_Bhv_PickUpSmall_SprintTurnAround
	, C_Bhv_PickUpSmall_Strafe_Aim_Shuffle_Left
	, C_Bhv_PickUpSmall_Strafe_Aim_Shuffle_Right
	, C_Bhv_PickUpSmall_Strafe_AimSpace_Charge_Down
	, C_Bhv_PickUpSmall_Strafe_AimSpace_Charge_Up
	, C_Bhv_PickUpSmall_Strafe_Bwd
	, C_Bhv_PickUpSmall_Strafe_Bwd_L
	, C_Bhv_PickUpSmall_Strafe_Bwd_R
	, C_Bhv_PickUpSmall_Strafe_Fwd
	, C_Bhv_PickUpSmall_Strafe_Fwd_L
	, C_Bhv_PickUpSmall_Strafe_Fwd_R
	, C_Bhv_PickUpSmall_Strafe_Left
	, C_Bhv_PickUpSmall_Strafe_MH
	, C_Bhv_PickUpSmall_Strafe_Right
	, C_Bhv_PickUpSmall_Throw
	, C_Bhv_PickUpSmall_WallSlide_Enter
	, C_Bhv_PickUpSmall_WallSlide_Enter_FromDash
	, C_Bhv_PickUpSmall_WallSlide_Enter_NotJumpable
	, C_Bhv_PickUpSmall_WallSlide_Jump
	, C_Bhv_PickUpSmall_WallSlide_MH
	, C_Bhv_pikUpSmall_Grind_Dash
	, C_Bhv_PlasmaBall_Enter
	, C_Bhv_PlasmaBall_Exit
	, C_Bhv_PlasmaBall_MH
	, C_Bhv_PlayRoom_LavaLampButton
	, C_Bhv_PlayRoom_MageCombat_Attack_Var1
	, C_Bhv_PlayRoom_MageCombat_Attack_Var1_2
	, C_Bhv_PlayRoom_MageCombat_Attack_Var1_3
	, C_Bhv_PlayRoom_MageCombat_Attack_Var2
	, C_Bhv_PlayRoom_MageCombat_Attack_Var2_2
	, C_Bhv_PlayRoom_MageCombat_Attack_Var2_3
	, C_Bhv_PlayRoom_MageCombat_Attack_Var3
	, C_Bhv_PlayRoom_MageCombat_Attack_Var3_2
	, C_Bhv_PlayRoom_MageCombat_Attack_Var3_3
	, C_Bhv_PlayRoom_MageCombat_Attack_Var3_4
	, C_Bhv_PlayRoom_MageCombat_BeamAttack
	, C_Bhv_PlayRoom_MageCombat_Blink_Exit
	, C_Bhv_PlayRoom_MageCombat_MH
	, C_Bhv_PlayRoom_MageCombat_OrbAttack
	, C_Bhv_PlayRoom_MageCombat_TakeDamage_Var1
	, C_Bhv_PlayRoom_MageCombat_TakeDamage_Var2
	, C_Bhv_PlayRoom_MageCombat_TakeDamage_Var3
	, C_Bhv_PlayRoom_SpinningSpaceLamp
	, C_Bhv_PlayRoom_ZeroGravity_AdditiveRotation_Fwd
	, C_Bhv_PlayRoom_ZeroGravity_AdditiveRotation_Right
	, C_Bhv_PlayRoom_ZeroGravity_Back
	, C_Bhv_PlayRoom_ZeroGravity_Fwd
	, C_Bhv_PlayRoom_ZeroGravity_Left
	, C_Bhv_PlayRoom_ZeroGravity_MH
	, C_Bhv_PlayRoom_ZeroGravity_Right
	, C_Bhv_Pull
	, C_Bhv_Push_Battery_Bck
	, C_Bhv_Push_Battery_Fwd
	, C_Bhv_Push_Battery_MH
	, C_Bhv_Push_Enter
	, C_Bhv_Push_Exit
	, C_Bhv_Push_Fwd
	, C_Bhv_Push_MH
	, C_Bhv_Push_Struggle
	, C_Bhv_PushButton_Var1
	, C_Bhv_PushButton_Var2
	, C_Bhv_PushButton_Var2_SapGun
	, C_Bhv_PutDown
	, C_Bhv_PutDown_InPlace
	, C_Bhv_RocketFirework
	, C_Bhv_Shed_VacuumLaunch_Enter
	, C_Bhv_Shed_VacuumLaunch_MH
	, C_Bhv_Skydive_Bwd
	, C_Bhv_Skydive_Fwd
	, C_Bhv_Skydive_Left
	, C_Bhv_Skydive_MH
	, C_Bhv_Skydive_Right
	, C_Bhv_Skydive_Start
	, C_Bhv_Swinging_Bck
	, C_Bhv_Swinging_Bck_Bck
	, C_Bhv_Swinging_Bck_Fwd
	, C_Bhv_Swinging_Bck_Left
	, C_Bhv_Swinging_Bck_Neutral
	, C_Bhv_Swinging_Bck_Right
	, C_Bhv_Swinging_Bck_TurnAround
	, C_Bhv_Swinging_Enter
	, C_Bhv_Swinging_ExitBck
	, C_Bhv_Swinging_ExitFwd
	, C_Bhv_Swinging_Fwd
	, C_Bhv_Swinging_JumpBck
	, C_Bhv_Swinging_JumpFwd
	, C_Bhv_Swinging_Left
	, C_Bhv_Swinging_Neutral
	, C_Bhv_Swinging_Right
	, C_Bhv_Swinging_TurnAround
	, C_Bhv_Valve_Rotate_MH
	, C_Bhv_Valve_Rotate_R
	, C_Bhv_Valve_Rotate_R_Short
	, C_Bhv_Valve_StruggleLeft
	, C_Bhv_Valve_StruggleLeft_MH
	, C_Bhv_Valve_StruggleLeftEnter
	, C_Bhv_Valve_StruggleRight
	, C_Bhv_Valve_StruggleRight_MH
	, C_Bhv_Valve_StruggleRightEnter
	, C_ChangeSize_Jump_Falling
	, C_ChangeSize_Jump_Large_Land
	, C_ChangeSize_Jump_Large_Land_Jog
	, C_ChangeSize_Jump_Start
	, C_ChangeSize_Roll_Start
	, C_ChangeSize_Walk_Large_Bank_Left
	, C_ChangeSize_Walk_Large_Bank_Right
	, C_ChangeSize_Walk_Large_Fwd
	, C_ChangeSize_Walk_Large_Start
	, C_ChangeSize_Walk_Large_Stop
	, C_Crouch_Enter_GroundPound
	, C_Crouch_Enter_Landing
	, C_Crouch_Enter_MH
	, C_Crouch_Enter_Slide
	, C_Crouch_Enter_SlideMovement
	, C_Crouch_Enter_Walk
	, C_Crouch_Exit_MH
	, C_Crouch_Exit_Movement
	, C_Crouch_Exit_Movement_Walk
	, C_Crouch_Fwd
	, C_Crouch_MH
	, C_Crouch_Start
	, C_Crouch_Stop
	, C_CutScene_BossFight_BeamOut
	, C_CutScene_BossFight_Eject
	, C_CutScene_BossFight_EnterUFO
	, C_CutScene_BossFight_Intro
	, C_CutScene_BossFight_LandInsideUFO
	, C_CutScene_BossFight_LaserRippedOff
	, C_CutScene_BossFight_Outro
	, C_CutScene_Hub_SecondGenerator
	, C_DoubleJump
	, C_Exhausted_MH
	, C_Exhausted_MH_To_Idle
	, C_Grind_Btn_Press
	, C_Grind_Btn_Ready
	, C_Grind_Dash
	, C_Grind_Fast_MH
	, C_Grind_Fast_MH_Left
	, C_Grind_Fast_MH_Right
	, C_Grind_Grapple_Enter
	, C_Grind_Grapple_ToGrind
	, C_Grind_Jump
	, C_Grind_Land
	, C_Grind_Slow_MH
	, C_Grind_Slow_MH_Left
	, C_Grind_Slow_MH_LookLeft
	, C_Grind_Slow_MH_LookRight
	, C_Grind_Slow_MH_ReachLeft
	, C_Grind_Slow_MH_ReachLeftDown
	, C_Grind_Slow_MH_ReachLeftUp
	, C_Grind_Slow_MH_ReachRight
	, C_Grind_Slow_MH_ReachRightDown
	, C_Grind_Slow_MH_ReachRightUp
	, C_Grind_Slow_MH_Right
	, C_Grind_Transfer_LandLeft
	, C_Grind_Transfer_LandRight
	, C_Grind_Transfer_Left
	, C_Grind_Transfer_Right
	, C_Grind_TurnAround_Boost
	, C_Grind_TurnAround_SlowDown
	, C_Grind_UpsideDown_Enter
	, C_Grind_UpsideDown_Exit
	, C_Grind_UpsideDown_Fast_MH
	, C_Grind_UpsideDown_Fast_MH_Left
	, C_Grind_UpsideDown_Fast_MH_Right
	, C_Grind_UpsideDown_Slow_MH
	, C_Grind_UpsideDown_Slow_MH_LEFT
	, C_Grind_UpsideDown_Slow_MH_RIGHT
	, C_Idle_To_Action
	, C_Idle_To_Exhausted
	, C_Jog
	, C_Jog_Action_MH_Start_Fwd
	, C_Jog_Bank_Left
	, C_Jog_Bank_Right
	, C_Jog_Exhausted_MH_Start_Fwd
	, C_Jog_GoToStop
	, C_Jog_LookBackL
	, C_Jog_LookBackR
	, C_Jog_Start_Fwd
	, C_Jog_Start_Fwd_Left_180
	, C_Jog_Start_Fwd_Right_180
	, C_Jog_Start_InMotion
	, C_Jog_Start_InMotion_Var2
	, C_Jog_Stop_Fwd
	, C_Jog_Stop_Fwd_Action
	, C_Jog_Stop_Fwd_Easy
	, C_Jog_Stop_Fwd_Exhausted
	, C_Jog_Strafe_Bwd
	, C_Jog_Strafe_Fwd
	, C_Jog_Strafe_Left
	, C_Jog_Strafe_Right
	, C_Jump_180L
	, C_Jump_180R
	, C_Jump_Falling
	, C_Jump_Falling_Backwards
	, C_Jump_Falling_Boosted
	, C_Jump_Falling_Boosted_Left
	, C_Jump_Falling_Boosted_Right
	, C_Jump_Falling_Boosted_Sucked
	, C_Jump_Falling_Forwards
	, C_Jump_Falling_Left
	, C_Jump_Falling_Right
	, C_Jump_FromDash
	, C_Jump_FromDashStop
	, C_Jump_Land
	, C_Jump_Land_Dash
	, C_Jump_Land_Dash_Jog
	, C_Jump_Land_Dash_Walk
	, C_Jump_Land_High
	, C_Jump_Land_High_Jog
	, C_Jump_Land_High_Jog_Cancel
	, C_Jump_Land_High_Jog_Jump
	, C_Jump_Land_High_Start_Still
	, C_Jump_Land_High_Start_Still_Walk
	, C_Jump_Land_High_Walk
	, C_Jump_Land_Jog
	, C_Jump_Land_Jog_Jump
	, C_Jump_Land_Jog_Jump_Var2
	, C_Jump_Land_Jog_Jump_Var3
	, C_Jump_Land_Jog_Jump_Var4
	, C_Jump_Land_Jog_Jump_Var5
	, C_Jump_Land_Jog_Jump_Var6
	, C_Jump_Land_PerfectDash
	, C_Jump_Land_PerfectDash_Jog
	, C_Jump_Land_PerfectDash_Walk
	, C_Jump_Land_Start_Still
	, C_Jump_Land_Start_Still_Walk
	, C_Jump_Land_Still_Jump
	, C_Jump_Land_Walk
	, C_Jump_LongJump
	, C_Jump_LongJump_PickUpSmall
	, C_Jump_LongJump_Var1
	, C_Jump_Start
	, C_Jump_WallClimb
	, C_Jump_WallClimb_SlideDown
	, C_JumpFromPerfectDash
	, C_JumpFromPerfectDashStop
	, C_LedgeGrab_ClimbLeft
	, C_LedgeGrab_ClimbRight
	, C_LedgeGrab_ClimbUp
	, C_LedgeGrab_Drop
	, C_LedgeGrab_JumpBack_Left
	, C_LedgeGrab_JumpBack_Right
	, C_LedgeGrab_JumpUp
	, C_LedgeGrab_MH
	, C_LedgeGrab_MH_Left120
	, C_LedgeGrab_MH_Left180
	, C_LedgeGrab_MH_Left30
	, C_LedgeGrab_MH_Left60
	, C_LedgeGrab_MH_Left90
	, C_LedgeGrab_MH_Right120
	, C_LedgeGrab_MH_Right180
	, C_LedgeGrab_MH_Right30
	, C_LedgeGrab_MH_Right60
	, C_LedgeGrab_MH_Right90
	, C_LedgeGrab_Start
	, C_LedgeVault
	, C_LedgeVaultStart
	, C_MH
	, C_PickUpSmall_Bhv_GroundPound_Land_Exit
	, C_PlasmaBall_Bwd
	, C_PlasmaBall_Bwd_Left
	, C_PlasmaBall_Bwd_Right
	, C_PlasmaBall_Fwd
	, C_PlasmaBall_Fwd_Left
	, C_PlasmaBall_Fwd_Right
	, C_PlasmaBall_Left
	, C_PlasmaBall_Right
	, C_PlayRoom_MageCombat_Jog
	, C_PlayRoom_MageCombat_Jog_Start_Fwd
	, C_PlayRoom_MageCombat_jog_Stop_Fwd
	, C_Roll_From_GroundPound
	, C_Roll_From_PerfectJump
	, C_Roll_Jog_From_PerfectDash
	, C_Roll_Jump
	, C_Roll_PerfectDash
	, C_Roll_PerfectJump
	, C_Roll_Start
	, C_Roll_Stop
	, C_Roll_Stop_From_PerfectDash
	, C_Roll_To_Jog
	, C_Roll_To_Walk
	, C_Roll_Walk_From_PerfectDash
	, C_SkyDiveLanding
	, C_SkyDiveLanding_Fwd
	, C_SkyDiveLanding_Walk
	, C_Slide_Enter
	, C_Slide_Enter_Dash
	, C_Slide_Enter_Falling
	, C_Slide_Enter_GroundPound
	, C_Slide_Exit_Falling
	, C_Slide_ExitToMovement
	, C_Slide_ExitToMovement_Walk
	, C_Slide_Fwd
	, C_Slide_Jump
	, C_Slide_Left
	, C_Slide_Right
	, C_Sprint
	, C_Sprint_Jump
	, C_Sprint_Left
	, C_Sprint_Right
	, C_Sprint_Start_FromDash
	, C_SprintTurnAround
	, C_Strafe_Bwd
	, C_Strafe_BwdL
	, C_Strafe_BwdR
	, C_Strafe_Fwd
	, C_Strafe_FwdL
	, C_Strafe_FwdR
	, C_Strafe_Left
	, C_Strafe_MH
	, C_Strafe_Right
	, C_Strafe_TurnInPlace_Left
	, C_Strafe_TurnInPlace_Right
	, C_Walk_Action_MH_Start_Fwd
	, C_Walk_Bank_Left
	, C_Walk_Bank_Right
	, C_Walk_Exhausted_MH_Start_Fwd
	, C_Walk_Fwd
	, C_Walk_Locomotion_Walk
	, C_Walk_Start_Fwd
	, C_Walk_Start_Fwd_Left_180
	, C_Walk_Start_Fwd_Right_180
	, C_Walk_Start_InMotion
	, C_Walk_Start_InMotion_Var2
	, C_WallRun_Left_Enter
	, C_WallRun_Left_Jump
	, C_WallRun_Left_Run
	, C_WallRun_Right_Enter
	, C_WallRun_Right_Jump
	, C_WallRun_Right_Run
	, C_WallSlide_Enter
	, C_WallSlide_Enter_FromDash
	, C_WallSlide_Enter_NotJumpable
	, C_WallSlide_Jump
	, C_WallSlide_Jump_Vertical
	, C_WallSlide_MH
	, C_WallSlide_MH_ReadyToDash
};

enum MAY_ANIM
{
	M_ActionMH
	, M_ActionMH_To_Idle
	, M_AirDash_Start
	, M_ArcadeScreenLever_Bck
	, M_ArcadeScreenLever_BckLeft
	, M_ArcadeScreenLever_BckRight
	, M_ArcadeScreenLever_Fwd
	, M_ArcadeScreenLever_FwdLeft
	, M_ArcadeScreenLever_FwdRight
	, M_ArcadeScreenLever_Left
	, M_ArcadeScreenLever_MH
	, M_ArcadeScreenLever_Right
	, M_ArcadeScreenLever_Trigger
	, M_Bounce1
	, M_Bounce2
	, M_Bounce3
	, M_Bounce4
	, M_BruteCombat_Attack_Var1
	, M_BruteCombat_Attack_Var2
	, M_BruteCombat_Attack_Var3
	, M_BruteCombat_Dash
	, M_BruteCombat_GroundSmash
	, M_BruteCombat_Jog
	, M_BruteCombat_MH
	, M_BruteCombat_Start_Fwd
	, M_BruteCombat_Stop
	, M_BruteCombat_TakeDamage_Heavy_Var1
	, M_BruteCombat_TakeDamage_Heavy_Var2
	, M_BruteCombat_TakeDamage_Heavy_Var3
	, M_BruteCombat_UltimatWhirlwind_MH
	, M_BruteCombat_WhirlWind_MH
	, M_Bump_Collide
	, M_Bump_Collide_Fall
	, M_ChessMiniGame_Gestures_Point_Var1
	, M_Controllable_Right
	, M_Crouch_Enter_GroundPound
	, M_Crouch_Enter_Landing
	, M_Crouch_Enter_MH
	, M_Crouch_Enter_Movement
	, M_Crouch_Enter_Slide
	, M_Crouch_Enter_Slide_Movement
	, M_Crouch_Exit_MH
	, M_Crouch_Exit_Movement
	, M_Crouch_Exit_Movement_Slow
	, M_Crouch_MH
	, M_Crouch_Walk
	, M_Crouch_Walk_Start
	, M_Crouch_Walk_Stop
	, M_CutScene_BeamUp_Intro_May
	, M_CutScene_SpaceStation_BossFight_BeamOut
	, M_CutScene_SpaceStation_BossFight_Eject
	, M_DashMoveTo_Start
	, M_DashMoveTo_Start_InAir
	, M_DashMoveTo_Start_Left90
	, M_DashMoveTo_Start_Right90
	, M_Death_Fall_MH
	, M_Death_Oil_Drown
	, M_DoubleJump
	, M_ExhaustedMH
	, M_ExhaustedMH_To_Idle
	, M_FidgetSpinner_Enter
	, M_FidgetSpinner_Exit
	, M_FidgetSpinner_Hover_Fast_MH
	, M_FidgetSpinner_Hover_Fast_MH_Left
	, M_FidgetSpinner_Hover_Fast_MH_Right
	, M_FidgetSpinner_Hover_Slow_MH
	, M_FidgetSpinner_Hover_Slow_MH_Left
	, M_FidgetSpinner_Hover_Slow_MH_Right
	, M_FidgetSpinner_InAir_Enter
	, M_FidgetSpinner_InAir_Exit
	, M_Grind_Btn_Press
	, M_Grind_Btn_Ready
	, M_Grind_Dash
	, M_Grind_Fast_MH
	, M_Grind_Fast_MH_Left
	, M_Grind_Fast_MH_LookLeft
	, M_Grind_Fast_MH_LookRight
	, M_Grind_Fast_MH_Right
	, M_Grind_Grapple_Enter
	, M_Grind_Grapple_ToGrind
	, M_Grind_Jump
	, M_Grind_Land
	, M_Grind_Slow_MH
	, M_Grind_Slow_MH_Left
	, M_Grind_Slow_MH_LookLeft
	, M_Grind_Slow_MH_LookRight
	, M_Grind_Slow_MH_ReachLeft
	, M_Grind_Slow_MH_ReachLeftDown
	, M_Grind_Slow_MH_ReachLeftUp
	, M_Grind_Slow_MH_ReachRight
	, M_Grind_Slow_MH_ReachRightDown
	, M_Grind_Slow_MH_ReachRightUp
	, M_Grind_Slow_MH_Right
	, M_Grind_Transfer_LandLeft
	, M_Grind_Transfer_LandRight
	, M_Grind_Transfer_Left
	, M_Grind_Transfer_Right
	, M_Grind_TurnAround_Boost
	, M_Grind_TurnAround_SlowDown
	, M_Grind_UpsideDown_Enter
	, M_Grind_UpsideDown_Exit
	, M_Grind_UpsideDown_Fast_Left
	, M_Grind_UpsideDown_Fast_MH
	, M_Grind_UpsideDown_Fast_Right
	, M_Grind_UpsideDown_Slow_Left
	, M_Grind_UpsideDown_Slow_MH
	, M_Grind_UpsideDown_Slow_Right
	, M_GroundPound_Falling
	, M_GroundPound_Jump_High
	, M_GroundPound_Jump_Low
	, M_GroundPound_Land
	, M_GroundPound_Land_Exit
	, M_GroundPound_Land_MH
	, M_GroundPound_Start
	, M_HoldButton_Enter
	, M_HoldButton_Exit
	, M_HoldButton_MH
	, M_Jog
	, M_Jog_Action_Start
	, M_Jog_Bank_Left
	, M_Jog_Bank_Right
	, M_Jog_Exhausted_Start
	, M_Jog_LookBackL
	, M_Jog_LookBackR
	, M_Jog_Start
	, M_Jog_Start_InMotion
	, M_Jog_Start_InMotion_Var2
	, M_Jog_Stop
	, M_Jog_Stop_Action
	, M_Jog_Stop_Easy
	, M_Jog_Stop_Exhausted
	, M_Jog_Turn_Left180
	, M_Jog_Turn_Right180
	, M_Jump_180L
	, M_Jump_180R
	, M_Jump_Falling
	, M_Jump_Falling_Bck
	, M_Jump_Falling_Boosted
	, M_Jump_Falling_Boosted_Left
	, M_Jump_Falling_Boosted_Right
	, M_Jump_Falling_Boosted_Sucked
	, M_Jump_Falling_Fwd
	, M_Jump_Falling_Left
	, M_Jump_Falling_right
	, M_Jump_FromDash
	, M_Jump_FromDashStop
	, M_Jump_FromPerfectDash
	, M_Jump_FromPerfectDashStop
	, M_Jump_Land
	, M_Jump_Land_Dash
	, M_Jump_Land_Dash_Jog
	, M_Jump_Land_Dash_Walk
	, M_Jump_Land_High
	, M_Jump_Land_High_Jog
	, M_Jump_Land_High_Walk
	, M_Jump_Land_Jog
	, M_Jump_Land_Jog_Jump
	, M_Jump_Land_Jog_Jump_Var2
	, M_Jump_Land_Jog_Jump_Var3
	, M_Jump_Land_PerfectDash
	, M_Jump_Land_PerfectDash_Jog
	, M_Jump_Land_PerfectDash_Walk
	, M_Jump_Land_Walk
	, M_Jump_LongJump
	, M_Jump_LongJump_PickUpSmall
	, M_Jump_Start
	, M_Jump_Start_Fwd
	, M_KnockDown_Back_Land
	, M_KnockDown_Back_MH
	, M_KnockDown_Back_Start
	, M_KnockDown_Front
	, M_KnockDown_Front_Land
	, M_KnockDown_Front_MH
	, M_KnockDown_Front_Start
	, M_KnockDown_Left_Land
	, M_KnockDown_Left_MH
	, M_KnockDown_Left_Start
	, M_KnockDown_Right_Land
	, M_KnockDown_Right_MH
	, M_KnockDown_Right_Start
	, M_LavaLampButton
	, M_LedgeGrab_ClimbUp
	, M_LedgeGrab_JumpBack_Left
	, M_LedgeGrab_JumpBack_Right
	, M_LedgeGrab_JumpUp
	, M_LedgeGrab_MH
	, M_LedgeGrab_MH_Left120
	, M_LedgeGrab_MH_Left180
	, M_LedgeGrab_MH_Left30
	, M_LedgeGrab_MH_Left60
	, M_LedgeGrab_MH_Left90
	, M_LedgeGrab_MH_Right120
	, M_LedgeGrab_MH_Right180
	, M_LedgeGrab_MH_Right30
	, M_LedgeGrab_MH_Right60
	, M_LedgeGrab_MH_Right90
	, M_LedgeGrab_Start
	, M_LedgeVault
	, M_LedgeVaultStart
	, M_Lever_Left
	, M_Lever_Right
	, M_LeverPull_Exit_Fast
	, M_LeverPull_Exit_Slow
	, M_LeverPull_MH
	, M_LeverPull_Start_Fast
	, M_MH
	, M_MH_Gesture_Big_Waiting_Enter
	, M_MH_Gesture_Big_Waiting_MH
	, M_MH_Gesture_Small_BrushOffDir
	, M_MH_Gesture_Small_InspectNamils
	, M_MH_Gesture_Small_Knock
	, M_MH_Gesture_Small_LookAround
	, M_MH_Gesture_Small_Stretch
	, M_MH_Gesture_Small_Watch
	, M_MH_To_Action
	, M_MH_To_Exhausted
	, M_MiniGame_Emotes_Applause
	, M_MiniGame_Emotes_Boxing
	, M_MiniGame_Emotes_Dance_Var1
	, M_MiniGame_Emotes_FlimsyDance
	, M_MIniGame_Emotes_FrontFlip
	, M_MiniGame_Emotes_Giggle
	, M_MiniGame_Emotes_Gunslinger
	, M_MIniGame_Emotes_Italian
	, M_MiniGame_Emotes_Lose_Var1
	, M_MiniGame_Emotes_Lose_Var2
	, M_MiniGame_Emotes_Lose_Var3
	, M_MIniGame_Emotes_Macarena
	, M_MiniGame_Emotes_ShoulderBrush
	, M_PickUp
	, M_PickUp_Aim_Strafe_Bwd
	, M_PickUp_Aim_Strafe_Fwd
	, M_PickUp_Aim_Strafe_Left
	, M_PickUp_Aim_Strafe_Right
	, M_PickUp_AimSpace_Center
	, M_PickUp_AimSpace_Down_BS
	, M_PickUp_AimSpace_Up_BS
	, M_PickUp_FuseCrab_PutInSocket
	, M_PickUp_Jog
	, M_PickUp_Jog_Stop
	, M_PickUp_Jump_Falling
	, M_PickUp_Jump_Land
	, M_PickUp_Jump_Land_Jog
	, M_PickUp_Jump_Start
	, M_PickUp_MH
	, M_PickUp_Throw
	, M_PickUpHeavySmall
	, M_PickUpHeavySmall_Jog
	, M_PickUpHeavySmall_Jog_Start
	, M_PickUpHeavySmall_Jog_Start_InMotion
	, M_PickUpHeavySmall_Jog_Stop
	, M_PickUpHeavySmall_Jump_Falling
	, M_PickUpHeavySmall_Jump_Land
	, M_PickUpHeavySmall_Jump_Land_Jog
	, M_PickUpHeavySmall_Jump_Start
	, M_PickUpHeavySmall_MH
	, M_PickUpHeavySmall_PutDown
	, M_PickUpHeavySmall_PutDown_InPlace
	, M_PickUpSamll_GroundPound_Land_MH
	, M_PickUpSamll_Swinging_Exit_Bck_Left
	, M_PickUpSmall
	, M_PickUpSmall_Aim_MH
	, M_PickUpSmall_Aim_Strafe_Bwd
	, M_PickUpSmall_Aim_Strafe_Fwd
	, M_PickUpSmall_Aim_Strafe_Left
	, M_PickUpSmall_Aim_Strafe_Right
	, M_PickUpSmall_AimSpace_Center
	, M_PickUpSmall_AimSpace_Down
	, M_PickUpSmall_AimSpace_Up
	, M_PickUpSmall_AirDash_Start
	, M_PickUpSmall_Bounce1
	, M_PickUpSmall_Bounce2
	, M_PickUpSmall_Bounce3
	, M_PickUpSmall_Bounce4
	, M_PickUpSmall_Grind_Dash
	, M_PickUpSmall_Grind_Fast_MH
	, M_PickUpSmall_Grind_Grapple_Enter
	, M_PickUpSmall_Grind_Grapple_ToGrind
	, M_PickUpSmall_Grind_Jump
	, M_PickUpSmall_Grind_Land
	, M_PickUpSmall_Grind_Slow_MH
	, M_PickUpSmall_Grind_Transfer_LandLeft
	, M_PickUpSmall_Grind_Transfer_LandRight
	, M_PickUpSmall_Grind_Transfer_Left
	, M_PickUpSmall_Grind_Transfer_Right
	, M_PickUpSmall_Grind_TurnAround_Boost
	, M_PickUpSmall_Grind_TurnAround_SlowDown
	, M_PickUpSmall_GroundPound_Falling
	, M_PickUpSmall_GroundPound_Jump_High
	, M_PickUpSmall_GroundPound_Jump_Low
	, M_PickUpSmall_GroundPound_Land_Exit
	, M_PickUpSmall_GroundPound_Start
	, M_PickUpSmall_Jog
	, M_PickUpSmall_Jog_Start
	, M_PickUpSmall_Jog_Start_InMotion
	, M_PickUpSmall_Jog_Stop
	, M_PickUpSmall_Jump_Falling
	, M_PickUpSmall_Jump_Land
	, M_PickUpSmall_Jump_Land_High
	, M_PickUpSmall_Jump_Land_Jog
	, M_PickUpSmall_Jump_Start
	, M_PickUpSmall_LedgeGrab_ClimbUp
	, M_PickUpSmall_LedgeGrab_JumpBack_Left
	, M_PickUpSmall_LedgeGrab_jumpUp
	, M_PickUpSmall_LedgeGrab_MH
	, M_PickUpSmall_LedgeGrab_MH_Left120
	, M_PickUpSmall_LedgeGrab_MH_Left180
	, M_PickUpSmall_LedgeGrab_MH_Left30
	, M_PickUpSmall_LedgeGrab_MH_Left60
	, M_PickUpSmall_LedgeGrab_MH_Left90
	, M_PickUpSmall_LedgeGrab_Start
	, M_PickUpSmall_LedgeVault
	, M_PickUpSmall_LedgeVaultStart
	, M_PickUpSmall_MH
	, M_PickUpSmall_PutDown
	, M_PickUpSmall_PutDown_InPlace
	, M_PickUpSmall_Roll_Jog_From_PerfectDash
	, M_PickUpSmall_Roll_PerfectDash
	, M_PickUpSmall_Roll_Start
	, M_PickUpSmall_Roll_Stop
	, M_PickUpSmall_Roll_Stop_From_PerfectDash
	, M_PickUpSmall_Roll_To_Jog
	, M_PickUpSmall_Sprint
	, M_PickUpSmall_Sprint_Left
	, M_PickUpSmall_Sprint_Right
	, M_PickUpSmall_Sprint_Start_FromDash
	, M_PickUpSmall_SprintTurnAround
	, M_PickUpSmall_Swinging_ApexTurn_Bck_Left
	, M_PickUpSmall_Swinging_ApexTurn_Bck_Right
	, M_PickUpSmall_Swinging_ApexTurn_Left
	, M_PickUpSmall_Swinging_ApexTurn_Right
	, M_PickUpSmall_Swinging_Bck_Fwd
	, M_PickUpSmall_Swinging_Bck_Left
	, M_PickUpSmall_Swinging_Bck_Right
	, M_PickUpSmall_Swinging_Enter
	, M_PickUpSmall_SwingIng_Enter_Left
	, M_PickUpSmall_Swinging_Enter_Right
	, M_PickUpSmall_Swinging_Exit_Bck_Right
	, M_PickUpSmall_Swinging_Exit_Fwd
	, M_PickUpSmall_Swinging_Fwd
	, M_PickUpSmall_Swinging_Left
	, M_PickUpSmall_Swinging_Right
	, M_PickUpSmall_Throw
	, M_PickUpSmall_WallSlide_Enter
	, M_PickUpSmall_WallSlide_Enter_FromDash
	, M_PickUpSmall_WallSlide_Enter_NotJumpable
	, M_PickUpSmall_WallSlide_Jump
	, M_PickUpSmall_WallSlide_MH
	, M_PinBall_Enter
	, M_PinBall_Exit
	, M_PinBall_HitLeft
	, M_PinBall_HitRight
	, M_PinBall_Left
	, M_PinBall_Left_Hit
	, M_PinBall_Left_HitStart
	, M_PinBall_MH
	, M_PinBall_MH_Hit
	, M_PinBall_MH_HitStart
	, M_PinBall_Right
	, M_PinBall_Right_Hit
	, M_PinBall_Right_HitStart
	, M_PlasmaCube_Bwd
	, M_PlasmaCube_Bwd_Left
	, M_PlasmaCube_Bwd_Right
	, M_PlasmaCube_Bwd_Struggle
	, M_PlasmaCube_BwdLeft_Struggle
	, M_PlasmaCube_BwdRight_Struggle
	, M_PlasmaCube_Enter
	, M_PlasmaCube_Exit
	, M_PlasmaCube_Fall_Enter
	, M_PlasmaCube_Fall_Exit
	, M_PlasmaCube_Fall_MH
	, M_PlasmaCube_Fwd
	, M_PlasmaCube_Fwd_Left
	, M_PlasmaCube_Fwd_Right
	, M_PlasmaCube_Fwd_Struggle
	, M_PlasmaCube_FwdLeft_Struggle
	, M_PlasmaCube_FwdRight_Struggle
	, M_PlasmaCube_Left
	, M_PlasmaCube_Left_Struggle
	, M_PlasmaCube_MH
	, M_PlasmaCube_Right
	, M_PlasmaCube_Right_Struggle
	, M_Pull
	, M_Push_Enter
	, M_Push_Exit
	, M_Push_Fwd
	, M_Push_MH
	, M_Push_Struggle
	, M_PushButton_Var1
	, M_PushButton_Var2
	, M_PushButton_Var2_Mirror
	, M_PushButton_Var2_Sniper
	, M_PutDown
	, M_PutDown_InPlace
	, M_Rocket_Down
	, M_Rocket_Enter
	, M_Rocket_Exit
	, M_Rocket_Left
	, M_Rocket_MH
	, M_Rocket_Right
	, M_Rocket_Up
	, M_RocketFirework
	, M_Roll_From_GroundPound
	, M_Roll_From_PerfectJump
	, M_Roll_Jog
	, M_Roll_Jog_From_PerfectDash
	, M_Roll_PerfectDash
	, M_Roll_PerfectJump
	, M_Roll_Start
	, M_Roll_Stop
	, M_Roll_Stop_From_PerfectDash
	, M_Roll_Walk
	, M_Roll_Walk_From_PerfectDash
	, M_Skydive_Falling
	, M_Skydive_Falling_Bck
	, M_Skydive_Falling_Fwd
	, M_Skydive_Falling_Left
	, M_Skydive_Falling_Right
	, M_Skydive_Start
	, M_SkyDiveLanding
	, M_SkyDiveLanding_Fwd
	, M_SkyDiveLanding_Walk
	, M_Slide_Enter
	, M_Slide_Enter_Dash
	, M_Slide_Enter_Falling
	, M_Slide_Enter_GroundPound
	, M_Slide_Exit_Falling
	, M_Slide_ExitToMovement
	, M_Slide_ExitToWalk
	, M_Slide_Fast_Neutral
	, M_Slide_Jump
	, M_Slide_Left
	, M_Slide_Netural
	, M_Slide_Right
	, M_SpacePortal_Exit
	, M_SpacePortal_Travel_MH
	, M_SpaceStation_BossFight_Intro
	, M_SpaceStation_BossFight_LaserRippedOff
	, M_SpaceStation_BossFight_Outro
	, M_SpaceStation_Hub_SecondGenerator
	, M_spinningSpaceLamp
	, M_Sprint
	, M_Sprint_Left
	, M_Sprint_Right
	, M_Sprint_Start_FromDash
	, M_SprintTurnAround
	, M_Strafe_Bwd
	, M_Strafe_BwdL
	, M_Strafe_BwdR
	, M_Strafe_Fwd
	, M_Strafe_FwdL
	, M_Strafe_FwdR
	, M_Strafe_L
	, M_Strafe_MH
	, M_Strafe_R
	, M_Strafe_TurnInPlace_Left
	, M_Strafe_TurnInPlace_Right
	, M_Swinging_ApexTurn_Bck_Left
	, M_Swinging_ApexTurn_Bck_Right
	, M_Swinging_ApexTurn_Left
	, M_Swinging_ApexTurn_Right
	, M_Swinging_Bck
	, M_Swinging_Bck_Left
	, M_Swinging_Bck_Right
	, M_Swinging_Enter
	, M_Swinging_Enter_Left
	, M_Swinging_Enter_Right
	, M_Swinging_Exit_Bck_Left
	, M_Swinging_Exit_Bck_Right
	, M_Swinging_Exit_Down
	, M_Swinging_Exit_Fwd
	, M_Swinging_Fwd
	, M_Swinging_Left
	, M_Swinging_Right
	, M_Ufo_Controllable_Left
	, M_Ufo_Controllable_MH
	, M_VacuumLaunch_Enter
	, M_Valve_Rotate_MH
	, M_Valve_Rotate_R
	, M_Valve_Rotate_R_Short
	, M_Valve_StruggleLeft
	, M_Valve_StruggleLeft_MH
	, M_Valve_StruggleLeftEnter
	, M_Valve_StruggleRight
	, M_Valve_StruggleRight_MH
	, M_Valve_StruggleRightEnter
	, M_Walk_Action_Start
	, M_Walk_Bank_Left
	, M_Walk_Bank_Right
	, M_Walk_Exhausted_Start
	, M_Walk_Fwd
	, M_Walk_Start
	, M_Walk_Start_InMotion
	, M_Walk_Start_InMotion_Var2
	, M_Walk_Turn_Left180
	, M_Walk_Turn_Right180
	, M_WalkIn
	, M_WallClimb_Down
	, M_WallClimb_Left
	, M_WallClimb_MH
	, M_WallClimb_Right
	, M_WallClimb_Up
	, M_WallRun_Left_Enter
	, M_WallRun_Left_Jump
	, M_WallRun_Left_Run
	, M_WallRun_Right_Enter
	, M_WallRun_Right_Jump
	, M_WallRun_Right_Run
	, M_WallSlide_Enter
	, M_WallSlide_Enter_From_Dash
	, M_WallSlide_Enter_NotJumpable
	, M_WallSlide_Jump
	, M_WallSlide_Jump_Vertical
	, M_WallSlide_MH
	, M_WallSlide_MH_ReadyToDash
	, M_ZeroGravity_AdditiveRotation_Fwd
	, M_ZeroGravity_AdditiveRotation_Ref
	, M_ZeroGravity_AdditiveRotation_Right
	, M_ZeroGravity_Bck
	, M_ZeroGravity_Fwd
	, M_ZeroGravity_MH

};
