#pragma once

namespace Engine
{
	struct GameID
	{
		enum Enum
		{
			eCODY,
			eMAY,
			eCAMERA,
			eMAINCAMERA,
			eSUBCAMERA,
			eUFO,
			eMOONBABOON,
			eSTARBUDDY,
			eSAVEPOINT,
			eDEADLINE,
			eROCKET,
			eROBOT,
			eROBOTHEAD,
			eROBOTBATTERY,
			eROBOTLEVER,
			eROTATEDROBOTBODY,
			eROTATEDROBOTHEAD,
			eVALVE,
			eUMBRELLA,
			eVERTICALDOOR,
			eBIGBUTTON,
			eBIGBUTTONFRAME,
			eROPEBASE,
			eGRINDRAIL,
			ePLANET,
			eNOBATTERYSIGN,
			eSPACEVALVE,
			eMAYJUMPWALL,
			ePIPEJUMPWALL,
			eDUMMYCOLLIDER,
			eGRAVITYPIPE,
			eHOOKUFO,
			eGRAVITYPATH,
			ePINBALL,
			eBLOCKED,
			ePINBALLHANDLE,
			ePINBALLDOOR,
			eWARPGATE,
			eWORMHOLE,
			eFIREDOOR,
			eBOSSMISSILE_COMBAT,
			eBOSSMISSILE_PLAYABLE,
			eGRAVITYPATH_CENTER,
			eGRAVITYPATH_SIDE,
			eSPACERAIL,
			eCONTROLROOMBATTERY,
			eBATTERYBOX,
			ePIPECURVE,
			ePRESSUREPLATE,
			ePRESSUREPLATEFRAME,
			ePRESSUREPLATELOCK,
			eSUPPORTFRAME,
			ePRESSUREBIGPLATE,
			eCONTROLROOMDOOR,
			eCONTROLROOMGLASS,
			eUMBRELLABEAM,
			eUMBRELLABEAMSTAND,
			eUMBRELLABEAMBASE,
			eUMBRELLABEAMJOYSTICK,
			eWALLLASERTRAP,
			eWALLLASERTRAP_BUTTON,
			eDUMMYWALL,
			eDUMMYWALLCAMERATRIGGER,
			eMAYWALLCAMERATRIGGER,
			ePIPEWALLCAMERATRIGGER,
			eENVIRONMENT,
			eHANGINGPLANET,
			eHOOKAHTUBE,
			eELECTRICBOX,
			eELECTRICWALL,
			eEJECTIONBUTTON,
			ePRESS,
			eROTATIONFAN,
			ePEDAL,
			eROTATIONBOX,
			eUFORADARLEVER,
			eMOONUFO,
			eLASERTENNISPOWERCOORD,
			eLASERTRIGGER,
			eLASER_LASERTENNIS,
			eRUNNINGMOONBABOON
		};
	};

	typedef struct tagUserData
	{
		GameID::Enum		eID;
		class CGameObject*	pGameObject;

		tagUserData() {}
		tagUserData(GameID::Enum _eID, class CGameObject* _pGameObject) : eID(_eID), pGameObject(_pGameObject) {}
	}USERDATA;

	struct TriggerStatus
	{
		enum Enum { eFOUND, eLOST };
	};

	struct ContactStatus
	{
		enum Enum { eFOUND, eLOST };
	};

	struct LightStatus
	{
		enum Enum { eDIRECTIONAL, eSTATIC, eDYNAMIC, eEND };
	};
}