#pragma once

#include "Base.h"
#include "./Fmod/fmod.h"

BEGIN(Engine)

enum ENGINE_DLL CHANNEL_TYPE
{
	/* Se */
	CHANNEL_BGM
	/* Yoon */
#pragma region Cody
	, CHANNEL_CODYB_GROUNDPOUND_LANDING_VOICE, CHANNEL_CODYB_JUMP, CHANNEL_CODYB_JUMP_LANDING, CHANNEL_CODYB_JUMP_VOICE, CHANNEL_CODYB_WALK,
	CHANNEL_CODYM_DASH, CHANNEL_CODYM_DASH_LANDING, CHANNEL_CODYM_DASH_ROLL, CHANNEL_CODYM_DEAD_BURN, CHANNEL_CODYM_DEAD_FALL,
	CHANNEL_CODYM_GROUNDPOUND, CHANNEL_CODYM_GROUNDPOUND_LANDING_VOICE, CHANNEL_CODYM_GROUNDPOUND_ROLL, CHANNEL_CODYM_JUMP,
	CHANNEL_CODYM_JUMP_DOUBLE_VOICE, CHANNEL_CODYM_JUMP_LANDING_VOICE, CHANNEL_CODYM_RESURRECTION, CHANNEL_CODYM_RUN, CHANNEL_CODYM_WALK, CHANNEL_CODYM_WALLJUMP,
	CHANNEL_CODYS_DASH_VOICE, CHANNEL_CODYS_GROUNDPOUND_LANDING_VOICE, CHANNEL_CODYS_JUMP_DOUBLE_VOICE, CHANNEL_CODYS_JUMP_LANDING_VOICE, CHANNEL_CODYS_JUMP_VOICE, CHANNEL_SIZE_BTOM, CHANNEL_SIZE_MTOB, CHANNEL_SIZE_MTOS, CHANNEL_SIZE_STOM,
#pragma endregion

#pragma region May
	CHANNEL_MAY_DASH, CHANNEL_MAY_DASH_LANDING, CHANNEL_MAY_DEAD_BURN, CHANNEL_MAY_DEAD_FALL, CHANNEL_MAY_GROUNDPOUND_LANDING, CHANNEL_MAY_GROUNDPOUND_ROLL, CHANNEL_MAY_GROUNDPOUND_ROLL_VOICE,
	CHANNEL_MAY_JUMP, CHANNEL_MAY_JUMP_DOUBLE, CHANNEL_MAY_JUMP_LANDING, CHANNEL_MAY_RESURRECTION, CHANNEL_MAY_RUN, CHANNEL_MAY_WALK, CHANNEL_MAY_WALLJUMP,
#pragma endregion

#pragma region General_Character
	CHANNEL_CHARACTER_DEAD_ELECTRICSHOCK, CHANNEL_CHARACTER_MINIGAME_DAMAGED, CHANNEL_CHARACTER_ROPE_RAIL,
	CHANNEL_CHARACTER_ROPE_UFO_CATCH, CHANNEL_CHARACTER_UFO_MOVE, CHANNEL_CHARACTER_UFO_RELEASE, CHANNEL_CHARACTER_UFO_THROW,
	CHANNEL_CHARACTER_SKYDIVING, CHANNEL_CHARACTER_WALLJUMP_SLIDE,
	CHANNEL_VOICE_CODY_1, CHANNEL_VOICE_CODY_2,
	CHANNEL_VOICE_MAY_1, CHANNEL_VOICE_MAY_2,
#pragma endregion

#pragma region Interactive_Sounds
	CHANNEL_BIGBUTTON_PRESS, CHANNEL_BRIDGE_ACTIVE,
	CHANNEL_ROBOT_BATTERY_IN, CHANNEL_ROBOT_BATTERY_OUT, CHANNEL_ROBOT_CODY_PUSH_BATTERY, CHANNEL_ROBOT_ACTIVE, CHANNEL_ROBOT_LEVER, CHANNEL_ROBOT_LEVER_BACK, CHANNEL_ROBOT_MOVE, CHANNEL_ROBOT_NOBATTERY,
	CHANNEL_GRAVITFIELD_CREATE, CHANNEL_GRAVITFIELD_DROP, CHANNEL_GRAVITFIELD_ON, CHANNEL_GRAVITFIELD_RISE,
	CHANNEL_INTERACTIVE_ROCKET, CHANNEL_INTERACTIVE_STAR_EXPLODE, CHANNEL_INTERACTIVE_STAR_EXPLODEFAIL

#pragma endregion

	/* Jin */
	, CHANNEL_BOSS
	/* Hye */
	, CHANNEL_LOGO
	, CHANNEL_BUTTON
	, CHANNEL_TUBE
	, CHANNEL_HANGINGPLANET
	, CHANNEL_LASERTENNIS
	, CHANNEL_LASERBUTTON
	, CHANNEL_LASERBUTTONLARGE
	, CHANNEL_LASERACTIVATION
	, CHANNEL_LASERPOWERCOORD
	, CHANNEL_PINBALL
	, CHANNEL_PINBALL_HANDLE
	, CHANNEL_PINBALL_BLOCKER
	, CHANNEL_PINBALL_DOOR
	, CHANNEL_PINBALL_HANDLEMOVE
	/* Jung */
	/* Taek */
	/* Jun */
	, CHANNEL_CUTSCENE
	, CHANNEL_END
};

class ENGINE_DLL CSound_Manager final : public CBase
{
	DECLARE_SINGLETON(CSound_Manager)
public:
	explicit CSound_Manager() = default;
	virtual ~CSound_Manager() = default;

public: /* Getter */
	_bool Is_Playing(CHANNEL_TYPE eChannel);

public: /* Setter */
	void Play_Sound(TCHAR* pSoundKey, CHANNEL_TYPE eChannel, _float fVolume, _bool bLoop);
	/* 채널에 사운드가 재생중일때 새로운 사운드 무시 */
	void Stop_Sound(CHANNEL_TYPE eChannel);
	void Stop_SoundAll();
	void Set_SoundVolume(CHANNEL_TYPE eChannel, _float fVolume);

	/* 사운드 이펙트 */

	/* 사운드 보간 */
	/* 사운드를 재생시킨 후 호출해야합니다.*/
	/* 첫번째 채널, 두번째 채널, 보간 스피드, 첫번째 사운드볼륨, 두번째 사운드볼륨 */
	/* 보간이 끝나면 첫번째 채널의 사운드는 자동 종료 됩니다. */
	void Lerp_Sound(CHANNEL_TYPE eFirstChannel, CHANNEL_TYPE eSecondChannel, _float fLerpSpeed, _float fFirstVolume, _float fSecondVolume);
	/* 사운드 페이드인아웃*/
	/* 채널, Type(true == FadeIn, False == FadeOut) , 보간 스피드, 볼륨*/
	void FadeInOut(CHANNEL_TYPE eFirstChannel, _bool bType, _float fLerpSpeed, _float fVolume);

public:
	HRESULT Ready_SoundManager();
	void Update_Sound(_double dTimeDelta);

private:
	typedef unordered_map<TCHAR*, FMOD_SOUND*> SOUNDS;
private:
	FMOD_SYSTEM*	m_pSystem = nullptr;
	FMOD_CHANNEL*	m_pChannel[CHANNEL_END];
	SOUNDS			m_Sounds;

	/* 사운드 이펙트 */
	CHANNEL_TYPE	m_eFirstChannel = CHANNEL_END;
	CHANNEL_TYPE	m_eSecondChannel = CHANNEL_END;
	_float			m_fFirstVolume = 0.f;
	_float			m_fSecondVolume = 0.f;
	_float			m_fMaxVolume = 0.f;
	_float			m_fLerpSpeed = 0.f;
	_bool			m_bLerp = false;

	_bool			m_bFadeInOut = false;
	_bool			m_bType = false;

private:
	HRESULT Add_Sound(char* pFilePath);

private:
	/* Update */
	void Lerp_Sound_Update(_double dTimeDelta);
	void FadeInOut_Sound_Update(_double dTimeDelta);

public:
	virtual void Free() override;
};

END