#pragma once

#include "Client_Defines.h"
#include "Character.h"

BEGIN(Engine)
class CRenderer;
class CTransform;
class CModel;
END

BEGIN(Client)
class CCody final : public CCharacter
{
#pragma region Enum_STATE
public:
	enum CODY_STATE {
		/* For.Wall Actions */
		ENTIRE_ANIMATIONS, WALLSLIDE_ENTER, WALLSLIDE_ENTER_FROMDASH, WALLSLIDE_ENTER_NOTJUMPABLE, WALLSLIDE_JUMP,
		WALLSLIDE_JUMP_VERTICAL, WALLSLIDE_IDLE, WALLSLIDE_IDLE_READYTODASH, WALLRUN_LEFT_ENTER,
		WALLRUN_LEFT_JUMP, WALLRUN_LEFT_RUN, WALLRUN_RIGHT_ENTER, WALLRUN_RIGHT_JUMP, WALLRUN_RIGHT_RUN,

		/* For.Slide Actions */
		SLIDE_ENTER, SLIDE_ENTER_DASH, SLIDE_ENTER_FALLING, SLIDE_ENTER_GROUNDPOUND, SLIDE_EXIT_FALLING,
		SLIDE_EXIT_TO_MOVEMENT, SLIDE_EXIT_TO_MOVEMENT_WALK, SLIDE_FWD, SLIDE_JUMP, SLIDE_LEFT, SLIDE_RIGHT,

		/* For.Roll Actions */
		AIRDASH_START, ROLL_FROM_GROUNDPOUND, ROLL_FROM_PERFECTJUMP, ROLL_JOG_FROM_PERFECTDASH, ROLL_JUMP,
		ROLL_PERFECTDASH, ROLL_PERFECTJUMP, ROLL_START, ROLL_STOP, ROLL_STOP_FROM_PERFECTDASH, ROLL_TO_JOG,
		ROLL_TO_WALK, ROLL_WALK_FROM_PERFECTDASH,

		/* For.LedgeGrab Actions */
		LEDGEVAULT, LEDGEVAULTSTART, LEDGEGRAB_CLIMBLEFT, LEDGEGRAB_CLIMBRIGHT, LEDGEGRAB_CLIMBUP, LEDGEGRAB_DROP,
		LEDGEGRAB_JUMPBACK_LEFT, LEDGEGRAB_JUMPBACK_RIGHT, LEDGEGRAB_JUMPUP, LEDGEGRAB_IDLE, LEDGEGRAB_IDLE_LEFT120,
		LEDGEGRAB_IDLE_LEFT180, LEDGEGRAB_IDLE_LEFT30, LEDGEGRAB_IDLE_LEFT60, LEDGEGRAB_IDLE_LEFT90,
		LEDGEGRAB_IDLE_RIGHT120, LEDGEGRAB_IDLE_RIGHT180, LEDGEGRAB_IDLE_RIGHT30, LEDGEGRAB_IDLE_RIGHT60, LEDGEGRAB_IDLE_RIGHT90,
		LEDGEGRAB_START,

		/* For.Jump Actions */
		DOUBLEJUMP, JUMP_180L, JUMP_180R, JUMP_FALLING, JUMP_FALLING_BACKWARDS, JUMP_FALLING_BOOSTED, JUMP_FALLING_BOOSTED_LEFT,
		JUMP_FALLING_BOOSTED_RIGHT, JUMP_FALLING_BOOSTED_SUCKED, JUMP_FALLING_FORWARDS, JUMP_FALLING_LEFT, JUMP_FALLING_RIGHT,
		JUMP_FROMDASH, JUMP_FROMDASHSTOP, JUMP_LAND, IDLE, JUMP_LAND_DASH, JUMP_LAND_DASH_JOG, JUMP_LAND_DASH_WALK, JUMP_LAND_HIGH,
		JUMP_LAND_HIGH_JOG, JUMP_LAND_HIGH_JOG_CANCEL, JUMP_LAND_HIGH_JOG_JUMP, JUMP_LAND_HIGH_START_STILL, JUMP_LAND_HIGH_START_STILL_WALK,
		JUMP_LAND_HIGH_WALK, JUMP_LAND_JOG, JUMP_LAND_JOG_JUMP, JUMP_LAND_JOG_JUMP_VAR2, JUMP_LAND_JOG_JUMP_VAR3, JUMP_LAND_JOG_JUMP_VAR4, JUMP_LAND_JOG_JUMP_VAR5, JUMP_LAND_JOG_JUMP_VAR6,
		JUMP_LAND_PERFECTDASH, JUMP_LAND_PERFECTDASH_JOG, JUMP_LAND_PERFECTDASH_WALK, JUMP_LAND_START_STILL, JUMP_LAND_START_STILL_WALK, JUMP_LAND_START_STILL_JUMP, JUMP_LAND_WALK, JUMP_LONGJUMP,
		JUMP_LONGJUMP_PICKUPSMALL, JUMP_LONGJUMP_VAR1, JUMP_START, JUMPFROMPERFECTDASH, JUMPFROMPERFECTDASHSTOP, SKYDIVELANDING, SKYDIVELANDING_FWD, SKYDIVELANDING_WALK, SPRINT_JUMP,

		/* For.Grind Actions (레일맵) */
		GRIND_BTN_PRESS, GRIND_BTN_READY, GRIND_DASH, GRIND_FAST_IDLE, GRIND_FAST_IDLE_LEFT, GRIND_FAST_IDLE_RIGHT, GRIND_GRAPPLE_ENTER, GRIND_GRAPPLE_TO_GRIND,
		GRIND_JUMP, GRIND_LAND, GRIND_SLOW_IDLE, GRIND_SLOW_IDLE_LEFT, GRIND_SLOW_IDLE_LOOKLEFT, GRIND_SLOW_IDLE_LOOKRIGHT, GRIND_SLOW_IDLE_REACHLEFT, GRIND_SLOW_IDLE_REACHLEFTDOWN, GRIND_SLOW_IDLE_REACHLEFTUP,
		GRIND_SLOW_IDLE_REACHRIGHT, GRIND_SLOW_IDLE_REACHRIGHTDOWN, GRIND_SLOW_IDLE_REACHRIGHTUP, GRIND_SLOW_IDLE_RIGHT,
		GRIND_TRANSFER_LANDLEFT, GRIND_TRANSFER_LANDRIGHT, GRIND_TRANSFER_LEFT, GRIND_TRANSFER_RIGHT, GRIND_TURNAROUND_BOOST, GRIND_TURNAROUND_SLOWDOWN,
		GRIND_UPSIDEDOWN_ENTER, GRIND_UPSIDEDOWN_EXIT, GRIND_UPSIDEDOWN_FAST_IDLE, GRIND_UPSIDEDOWN_FAST_IDLE_LEFT, GRIND_UPSIDEDOWN_FAST_IDLE_RIGHT,
		GRIND_UPSIDEDOWN_SLOW_IDLE, GRIND_UPSIDEDOWN_SLOW_IDLE_LEFT, GRIND_UPSIDEDOWN_SLOW_IDLE_RIGHT,

		/* For.Crouch Actions (웅크리기) */
		CROUCH_ENTER_GROUNDPOUND, CROUCH_ENTER_LANDING, CROUCH_ENTER_IDLE, CROUCH_ENTER_SLIDE, CROUCH_ENTER_SLIDEMOVEMENT, CROUCH_ENTER_WALK,
		CROUCH_EXIT_IDLE, CROUCH_EXIT_MOVEMENT, CROUCH_EXIT_MOVEMENT_WALK,
		CROUCH_FWD, CROUCH_IDLE, CROUCH_START, CROUCH_STOP,

		/* For.etc (순서 이상하게 들어간 친구들) */
		JUMP_WALLCLIMB, JUMP_WALLCLIMB_SLIDEDOWN, ACTIONIDLE, ACTIONIDLE_TO_IDLE, EXHAUSTED_IDLE, EXHAUSTED_IDLE_TO_IDLE,
		IDLE_TO_ACTION, IDLE_TO_EXHAUSTED,

		/* For.Jog Actions (CapsLock 안누를 때 달리기) */
		JOG, JOG_ACTION_IDLE_START_FWD, JOG_BANK_LEFT, JOG_BANK_RIGHT,
		JOG_EXHAUSTED_IDLE_START_FWD, JOG_GOTOSTOP, JOG_LOOKBACKLEFT, JOG_LOOKBACKRIGHT, JOG_START_FWD, JOG_START_FWD_LEFT_180, JOG_START_FWD_RIGHT_180,
		JOG_START_INMOTION, JOG_START_INMOTION_VAR2, JOG_STOP_FWD, JOG_STOP_FWD_ACTION, JOG_STOP_FWD_EASY, JOG_STOP_FWD_EXHAUSTED,
		JOG_STRAFE_BWD, JOG_STRAFE_FWD, JOG_STRAFE_LEFT, JOG_STRAFE_RIGHT,

		/* For.Sprint Actions (CapsLock 눌렀을 때 달리기) */
		SPRINT, SPRINT_LEFT, SPRINT_RIGHT, SPRINT_START_FROMDASH, SPRINTTURNAROUND,
		STRAFE_BWD, STRAFE_BWDL, STRAFE_BWDR, STRAFE_FWD, STRAFE_FWDL, STRAFE_FWDR, STRAFE_LEFT, STRAFE_IDLE, STRAFE_RIGHT, STRAFE_TURNINPLACE_LEFT, STRAFE_TURNINPLACE_RIGHT,

		/* For.Walk Actions (걷기가 있나.) */
		WALK_ACTION_IDLE_START_FWD, WALK_BANK_LEFT, WALK_BANK_RIGHT, WALK_EXHAUSTED_IDLE_START_FWD, WALK_FWD, WALK_START_FWD, WALK_START_LEFT_180, WALK_START_RIGHT_180, WALK_START_INMOTION, WALK_START_INMOTION_VAR2,
		WALK_LOCOMOTION_WALK,

		/* For.Bounce Actions (점프 발판(쿠션) 밟을 때) */
		BHV_BOUNCE1, BHV_BOUNCE2, BHV_BOUNCE3, BHV_BOUNCE4, BHV_PICKUPSMALL_BOUNCE1, BHV_PICKUPSMALL_BOUNCE2, BHV_PICKUPSMALL_BOUNCE3, BHV_PICKUPSMALL_BOUNCE4,

		/* For.Bump Collide Actions (충돌했을때?) */
		BHV_BUMP_COLLIDE, BHV_BUMP_COLLIDE_FALL,

		/* For.Death Actions (사망) */
		BHV_DEATH_FALL_IDLE, BHV_DEATH_OIL_DROWN,

		/* For.GroundPound Actions (점프 후 내려찍기) */
		BHV_GROUNDPOUND_FALLING, BHV_GROUNDPOUND_JUMP_HIGH, BHV_GROUNDPOUND_JUMP_LOW,
		BHV_GROUNDPOUND_LAND, BHV_GROUNDPOUND_LAND_EXIT, BHV_GROUNDPOUND_LAND_IDLE, BHV_GROUNDPOUND_START,

		/* For.KnockDown Actions (넉백) */
		BHV_KNOCKDOWN_BACK_LAND, BHV_KNOCKDOWN_BACK_IDLE, BHV_KNOCKDOWN_BACK_START, BHV_KNOCKDOWN_FRONT, BHV_KNOCKDOWN_FRONT_LAND, BHV_KNOCKDOWN_FRONT_IDLE, BHV_KNOCKDOWN_FRONT_START,
		BHV_KNOCKDOWN_LEFT_LAND, BHV_KNOCKDOWN_LEFT_IDLE, BHV_KNOCKDOWN_LEFT_START, BHV_KNOCKDOWN_RIGHT_LAND, BHV_KNOCKDOWN_RIGHT_IDLE, BHV_KNOCKDOWN_RIGHT_START,

		/* For.Lever Actions (좌우 레버(배터리 넣는 로봇)) */
		BHV_LEVER_LEFT, BHV_LEVER_RIGHT,

		/* For.MiniGame Emote Actions (이모트 액션들 ㅇㅇ) */
		BHV_MINIGAME_EMOTES_ASSDANCE, BHV_MINIGAME_EMOTES_COSSACKDANCE, BHV_MINIGAME_EMOTES_EXPLOSION, BHV_MINIGAME_EMOTES_FISTPUMP, BHV_MINIGAME_EMOTES_FONZIE, BHV_MINIGAME_EMOTES_HAPPYDANCE, BHV_MINIGAME_EMOTES_HUZZAH, BHV_MINIGAME_EMOTES_JUMPUPLAND, BHV_MINIGAME_EMOTES_KARATEBOW, BHV_MINIGAME_EMOTES_LEAFFLEX,
		BHV_MINIGAME_EMOTES_LOSE_VAR1, BHV_MINIGAME_EMOTES_LOSE_VAR2, BHV_MINIGAME_EMOTES_LOSE_VAR3, BHV_MINIGAME_EMOTES_SHOULDERBRUSH, BHV_MINIGAME_EMOTES_WATCHINGYOU, BHV_MINIGAME_EMOTES_WEIRDROBOT,

		/* For.PickUp Actions (등에 짊어지거나 손에 들고있을 때 행동들) */
		BHV_PICKUP, BHV_PICKUP_AIM_STRAFE_BWD, BHV_PICKUP_AIM_STRAFE_FWD, BHV_PICKUP_AIM_STRAFE_LEFT, BHV_PICKUP_AIM_STRAFE_RIGHT,
		BHV_PICKUP_AIMSPACE_CENTER, BHV_PICKUP_IDLE, BHV_PICKUP_AIMSPACE_DOWN, BHV_PICKUP_AIMSPACE_UP, BHV_PICKUP_FUSECRAB_PUTINSOCKET,
		BHV_PICKUP_JOG, BHV_PICKUP_JOG_STOP, BHV_PICKUP_THROW, BHV_PICKUP_JUMP_FALLING, BHV_PICKUP_JUMP_LAND, BHV_PICKUP_JUMP_LAND_JOG,
		BHV_JUMP_START,
		BHV_PICKUP_HEAVYSMALL_JOG, BHV_PICKUP_HEAVYSMALL_JOG_STARTINMOTION, BHV_PICKUP_HEAVYSMALL_JOG_STOP, BHV_PICKUP_HEAVYSMALL_IDLE, BHV_PICKUP_HEAVYSMALL_PICKUP, BHV_PICKUP_HEAVYSMALL_PUTDOWN, BHV_PICKUP_HEAVYSMALL_PUTDOWN_INPLACE,
		BHV_PICKUP_HEAVYSMALL_JUMP_FALLING, BHV_PICKUP_HEAVYSMALL_JUMP_LAND, BHV_PICKUP_HEAVYSMALL_JUMP_LAND_JOG, BHV_PICKUP_HEAVYSMALL_JUMP_START,
		BHV_PICKUPSMALL, BHV_PICKUPSMALL_AIM_IDLE, BHV_PICKUPSMALL_AIM_STRAFE_FWD, BHV_PICKUPSMALL_AIMSPACE_DOWN, BHV_PICKUPSMALL_AIMSPACE_UP,
		BHV_PICKUPSMALL_BHV_GROUNDPOUND_FALLING, BHV_PICKUPSMALL_BHV_GROUNDPOUND_JUMP_HIGH, BHV_PICKUPSMALL_BHV_GROUNDPOUND_JUMP_LOW, BHV_PICKUPSMALL_BHV_GROUND_POUND_LAND,
		BHV_PICKUPSMALL_BHV_GROUNDPOUND_LAND_EXIT, BHV_PICKUPSMALL_BHV_GROUNDPOUND_LAND_IDLE, BHV_PICKUPSMALL_BHV_START,

		BHV_PICKUP_SMALL_BHV_SWINGING_BCK, BHV_PICKUP_SMALL_BHV_SWINGING_BCK_BCK, BHV_PICKUP_SMALL_BHV_SWINGING_BCK_FWD, BHV_PICKUP_SMALL_BHV_SWINGING_BCK_NEUTRAL, BHV_PICKUP_SMALL_BHV_SWINGING_BCK_TURNAROUND,
		BHV_PICKUP_SMALL_BHV_SWINGING_EXITBCK, BHV_PICKUP_SMALL_BHV_SWINGING_EXITFWD, BHV_PICKUP_SMALL_BHV_SWINGING_FWD, BHV_PICKUP_SMALL_BHV_SWINGING_JUMPBCK, BHV_PICKUP_SMALL_BHV_SWINGING_JUMPFWD, BHV_PICKUP_SMALL_BHV_SWINGING_NEUTRAL, BHV_PICKUP_SMALL_BHV_SWINGING_TURNAROUND,
		BHV_PICKUP_SMALL_JOG, BHV_PICKUP_SMALL_JOG_GOTOSTOP, BHV_PICKUP_SMALL_JOG_START_FWD, BHV_PICKUP_SMALL_JOG_START_INMOTION, BHV_PICKUP_SMALL_JOG_STOP_FWD,
		BHV_PICKUP_SMALL_SPRINT, BHV_PICKUP_SMALL_SPRINTSTARTFROMDASH, BHV_PICKUP_SMALL_SPRINTTURNAROUND, BHV_PICKUP_SMALL_IDLE, BHV_PICKUP_SMALL_PUTDOWN, BHV_PICKUP_SMALL_INPLACE,
		BHV_PICKUP_SMALL_STRAFE_AIM_SHUFFLE_LEFT, BHV_PICKUP_SMALL_STRAFE_AIM_SHUFFLE_RIGHT, BHV_PICKUP_SMALL_STRAFE_AIMSPACE_CHARGE_DOWN, BHV_PICKUP_SMALL_STRAFE_IDLE, BHV_PICKUP_SMALL_STRAFE_AIMSPACE_CHARGE_UP,
		BHV_PICKUP_SMALL_STRAFE_BWD, BHV_PICKUP_SMALL_STRAFE_BWD_L, BHV_PICKUP_SMALL_STRAFE_BWD_R, BHV_PICKUP_SMALL_STRAFE_FWD, BHV_PICKUP_SMALL_STRAFE_FWD_L, BHV_PICKUP_SMALL_STRAFE_FWD_R,
		BHV_PICKUP_SMALL_STRAFE_LEFT, BHV_PICKUP_SMALL_STRAFE_RIGHT, BHV_PICKUP_SMALL_THROW, BHV_PICKUP_SMALL_AIRDASHSTART, BHV_PICKUP_SMALL_DOUBLEJUMP,
		BHV_PICKUP_SMALL_GRIND_DASH, BHV_PICKUP_SMALL_GRIND_FAST, BHV_PICKUP_SMALL_GRIND_FAST_IDLE_LEFT, BHV_PICKUP_SMALL_GRIND_FAST_IDLE_RIGHT, BHV_PICKUP_SMALL_GRIND_GRAPPLE_ENTER, BHV_PICKUP_SMALL_GRIND_GRAPPLE_TOGRIND,
		BHV_PICKUP_SMALL_GRIND_JUMP, BHV_PICKUP_SMALL_GRIND_LAND, BHV_PICKUP_SMALL_GRIND_SLOW_IDLE, BHV_PICKUP_SMALL_GRIND_SLOW_IDLE_LEFT, BHV_PICKUP_SMALL_GRIND_SLOW_IDLE_RIGHT,
		BHV_PICKUP_SMALL_GRIND_TURNAROUND_BOOST, BHV_PICKUP_SMALL_GRIND_TURNAROUND_SLOWDOWN,
		BHV_PICKUPSMALL_JUMP_FALLING, BHV_PICKUPSMALL_JUMP_FROM_LANDING, BHV_PICKUPSMALL_JUMP_LAND, BHV_PICKUPSMALL_JUMP_LAND_JOG, BHV_PICKUPSMALL_JUMP_START, BHV_PICKUPSMALL_JUMP_STARTFROMSTILL,
		BHV_PICKUPSMALL_LEDGEGRAB_CLIMBUP, BHV_PICKUPSMALL_LEDGEGRAB_DROP, BHV_PICKUPSMALL_LEDGEGRAB_JUMPBACK_LEFT, BHV_PICKUPSMALL_LEDGEGRAB_JUMPUP, BHV_PICKUPSMALL_LEDGEGRAB_IDLE, BHV_PICKUPSMALL_LEDGEGRAB_IDLE_LEFT120, BHV_PICKUPSMALL_LEDGEGRAB_IDLE_LEFT180, BHV_PICKUPSMALL_LEDGEGRAB_IDLE_LEFT30, BHV_PICKUPSMALL_LEDGEGRAB_IDLE_LEFT60, BHV_PICKUPSMALL_LEDGEGRAB_IDLE_LEFT90,
		BHV_PICKUPSMALL_LEDGEGRAB_START, BHV_PICKUPSMALL_LEDGEVAULT, BHV_PICKUPSMALL_LEDGEVAULTSTART, BHV_PICKUPSMALL_PERFECTDASH, BHV_PICKUPSMALL_PERFECTDASHJOG, BHV_PICKUPSMALL_PERFECTDASHSTOP, BHV_PICKUPSMALL_ROLL_START, BHV_PICKUPSMALL_ROLL_STOP, BHV_PICKUPSMALL_ROLL_TO_JOG,
		BHV_PICKUPSMALL_WALLSLIDE_ENTER, BHV_PICKUPSMALL_WALLSLIDE_ENTER_FROMDASH, BHV_PICKUPSMALL_WALLSLIDE_ENTER_NOTJUMPABLE, BHV_PICKUPSMALL_WALLSLIDE_JUMP, BHV_PICKUPSMALL_WALLSLIDE_IDLE,

		/* For.PutDown Actions (내려놓기) */
		BHV_PUTDOWN, BHV_PUTDOWN_INPLACE,

		/* For. Pull/Push Actions */
		BHV_PULL, BHV_PUSH_ENTER, BHV_PUSH_EXIT, BHV_PUSH_FWD, BHV_PUSH_IDLE, BHV_PUSH_STRUGGLE,
		BHV_HOLDBUTTON_ENTER, BHV_HOLDBUTTON_EXIT, BHV_HOLDBUTTON_IDLE, BHV_PUSHBUTTON_VAR1, BHV_PUSHBUTTON_VAR2, BHV_PUSHBUTTON_VAR2_SAPGUN,

		/* For.Skydive Actions (낙하) */
		BHV_SKYDIVE_BWD, BHV_SKYDIVE_FWD, BHV_SKYDIVE_LEFT, BHV_SKYDIVE_IDLE, BHV_SKYDIVE_RIGHT, BHV_SKYDIVE_START,

		/* For.Swinging Actions (스윙) */
		BHV_SWINGING_BCK, BHV_SWINGING_BCK_BCK, BHV_SWINGING_BCK_FWD, BHV_SWINGING_BCK_LEFT, BHV_SWINGING_BCK_NEUTRAL, BHV_SWINGING_BCK_RIGHT, BHV_SWINGING_BCK_TURNAROUND,
		BHV_SWINGING_ENTER, BHV_SWINGING_EXITBCK, BHV_SWINGING_EXITFWD, BHV_SWINGING_FWD, BHV_SWINGING_JUMPBCK, BHV_SWINGING_JUMPFWD, BHV_SWINGING_LEFT, BHV_SWINGING_NEUTRAL, BHV_SWINGING_RIGHT, BHV_SWINGING_TURNAROUND,

		/* For.ChangeSize Actions (덩치 커졌을 때?) */
		CHANGESIZE_GROUNDPOUND_FALLING, CHANGESIZE_GROUNDPOUND_LAND_EXIT, CHANGESIZE_GROUNDPOUND_LAND_IDLE, CHANGESIZE_GROUNDPOUND_START,
		CHAGESIZE_PLANETPUSH_LARGE, CHAGESIZE_PLANETPUSH_MEDIUM, CHAGESIZE_PLANETPUSH_SMALL,
		CHANGESIZE_WALK_LARGE_BANK_LEFT, CHANGESIZE_WALK_LARGE_BANK_RIGHT, CHANGESIZE_WALK_LARGE_FWD, CHANGESIZE_WALK_LARGE_START, CHANGESIZE_WALK_LARGE_STOP,
		CHANGESIZE_JUMP_FALLING, CHANGESIZE_JUMP_LARGE_LAND, CHANGESIZE_JUMP_LARGE_LAND_JOG, CHANGESIZE_JUMP_START, CHANGESIZE_ROLL_START,

		/* For.FidgetSpinner Actions (피젯스피너 안쓸듯?) */
		FIDGETSPINNER_ENTER, FIDGETSPINNER_EXIT, FIDGETSPINNER_HOVER_FAST_IDLE, FIDGETSPINNER_HOVER_FAST_IDLE_LEFT, FIDGETSPINNER_HOVER_FAST_IDLE_RIGHT,
		FIDGETSPINNER_HOVER_SLOW_IDLE, FIDGETSPINNER_HOVER_SLOW_IDLE_LEFT, FIDGETSPINNER_HOVER_SLOW_IDLE_RIGHT,
		FIDGETSPINNER_INAIR_ENTER, FIDGETSPINNER_INAIR_EXIT,

		/* For.PlayRoom_Mage Actions (안쓸듯ㅇㅇ) */
		LAVALAMPBUTTON, MAGECOMBAT_ATTACK_1, MAGECOMBAT_ATTACK_2, MAGECOMBAT_ATTACK_3, MAGECOMBAT_ATTACK_4, MAGECOMBAT_ATTACK_5, MAGECOMBAT_ATTACK_6, MAGECOMBAT_ATTACK_7, MAGECOMBAT_ATTACK_8, MAGECOMBAT_ATTACK_9, MAGECOMBAT_ATTACK_10,
		MAGECOMBAT_BEAMATTACK, MAGECOMBAT_BLINK_EXIT, MAGECOMBAT_IDLE, MAGECOMBAT_ORBATTACK, MAGECOMBAT_DAMAGED1, MAGECOMBAT_DAMAGED2, MAGECOMBAT_DAMAGED3, MAGECOMBAT_JOG, MAGECOMBAT_JOG_START_FWD, MAGECOMBAT_JOG_STOP_FWD,

		/* For.PlasmaBall Actions (플라즈마공 안할 듯?)*/
		PLASAMABALL_ENTER, PLASAMABALL_EXIT, PLASAMABALL_IDLE, PLASAMABALL_BWD, PLASAMABALL_BWD_LEFT, PLASAMABALL_BWD_RIGHT, PLASAMABALL_FWD, PLASAMABALL_FWD_LEFT, PLASAMABALL_FWD_RIGHT,
		PLASAMABALL_LEFT, PLASAMABALL_RIGHT,

		/* For.Battery Actions (무조건 써야함 ㅇㅇ) */
		PUSH_BATTERY_BCK, PUSH_BATTERY_FWD, PUSH_BATTERY_IDLE,

		/* 그외의 다양한 상호작용 상태들 */
		SPINNINGSPACELAMP,
		ZEROGRAVITY_ADDITIVEROTATION_FWD, ZEROGRAVITY_ADDITIVEROTATION_RIGHT, ZEROGRAVITY_BACK, ZEROGRAVITY_FWD, ZEROGRAVITY_LEFT, ZEROGRAVITY_IDLE, ZEROGRAVITY_RIGHT,
		SHED_VACUUMLAUNCH_ENTER, SHED_VACUUMLAUNCH_IDLE,

		/* 밸브 돌리기 */
		VALVE_ROTATE_IDLE, VALVE_ROTATE_RIGHT, VALVE_ROTATE_RIGHT_SHORT, VALVE_STRUGGLELEFT, VALVE_STRUGGLELEFT_IDLE, VALVE_STRUGGLELEFTENTER,
		VALVE_STRUGGLERIGHT, VALVE_STRUGGLERIGHT_IDLE, VALVE_STRUGGLERIGHTENTER,

		/* 짜잘한 이동 상태들 */
		GENERIC_WALKIN, CHESSMINIGAME_GESTURES_POINT, DASHMOVETO_START, DASHMOVETO_START_INAIR, DASHMOVETO_START_LEFT90, DASHMOVETO_START_RIGHT90,
		IDLE_GESTURE_BIG_WAITING_ENTER, IDLE_GESTURE_BIG_WAITING_IDLE, IDLE_GESTURE_SMALL_ADJUSTLEAF, IDLE_GESTURE_SMALL_BELLY, IDLE_GESTURE_SMALL_DRUMMING, IDLE_GESTURE_SMALL_INSPECTNAILS,
		IDLE_GESTURE_SMALL_LOOKAROUND, IDLE_GESTURE_SMALL_SCRATCH, IDLE_GESTURE_SMALL_STRETCH, IDLE_GESTURE_SMALL_TOSSLEAF,

		/* 레버 당기는 상태 */
		LEVERPULL_EXIT_FAST, LEVERPULL_EXIT_SLOW, LEVERPULL_IDLE, LEVERPULL_START_FAST,

		/* 아케이드 미니게임 (안쓸듯) */
		ACRADESCREENLEVER_BCK, ACRADESCREENLEVER_BCKLEFT, ACRADESCREENLEVER_BCKRIGHT, ACRADESCREENLEVER_FWD, ACRADESCREENLEVER_FWDLEFT, ACRADESCREENLEVER_FWDRIGHT,
		ACRADESCREENLEVER_LEFT, ACRADESCREENLEVER_IDLE, ACRADESCREENLEVER_RIGHT, ACRADESCREENLEVER_TRIGGER,

		/* 로켓 날리기 ㅋ */
		ROCKETFIREWORK,

		/* 보스 컷씬들 */
		CUTSCENE_BOSSFIGHT_BEAMOUT, CUTSCENE_BOSSFIGHT_EJECT, CUTSCENE_BOSSFIGHT_ENTERUFO, CUTSCENE_BOSSFIGHT_INTRO, CUTSCENE_BOSSFIGHT_LANDINSIDE_UFO,
		CUTSCENE_BOSSFIGHT_OUTRO, CUTSCENE_BOSSFIGHT_LASER_RIPPED_OFF, CUTSCENE_HUB_SECOND_GENERATOR,


	};
#pragma endregion

public:
	enum PLAYER_SIZE { SIZE_SMALL, SIZE_MEDIUM, SIZE_LARGE, SIZE_END };

private:
	explicit CCody(ID3D11Device* pDevice, ID3D11DeviceContext* pDeviceContext);
	explicit CCody(const CCody& rhs);
	virtual ~CCody() = default;

	// 부모로 부터 상속
public:
	virtual HRESULT	NativeConstruct_Prototype() override;
	virtual HRESULT	NativeConstruct(void* pArg) override;
	virtual _int	Tick(_double dTimeDelta) override;
	virtual _int	Late_Tick(_double dTimeDelta) override;
	virtual HRESULT	Render() override;

public:
	virtual HRESULT Render_ShadowDepth() override;

public:
	CTransform* Get_Transform() { return m_pTransformCom; }

	// Tick 에서 호출될 함수들
private:
	virtual void KeyInput(_double dTimeDelta);

private:
	// 단발성 함수들.
	HRESULT Ready_Component();
	void Add_LerpInfo_To_Model();

	// Components
private:
	class CMainCamera*	m_pCamera = nullptr;

	// 생성 및 소멸 관련
public:
	static CCody* Create(ID3D11Device * pDevice, ID3D11DeviceContext * pDeviceContext);
	virtual CGameObject* Clone_GameObject(void* pArg) override;
	virtual void Free() override;

	

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////    상태 변환 관련 변수들   /////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
public:
	// 상태 && 이동
	void Move(const _double dTimeDelta);
	void Roll(const _double dTimeDelta);
	void Sprint(const _double dTimeDelta);
	void Jump(const _double dTimeDelta);
	void Change_Size(const _double dTimeDelta);
	void Ground_Pound(const _double dTimeDelta);
	_bool Trigger_End(const _double dTimeDelta);
	_bool Trigger_Check(const _double dTimeDelta);


#pragma region BasicMovement
private:
	// 상태
	CODY_STATE m_iCurState = CUTSCENE_HUB_SECOND_GENERATOR;
	CODY_STATE m_iNextState = CUTSCENE_HUB_SECOND_GENERATOR;


	// 기본 움직임
	_bool m_bSprint = false;
	_bool m_bRoll = false;
	_bool m_bMove = false;
	_bool m_bShortJump = false;
	_bool m_bGroundPound = false;
	_bool m_IsTurnAround = false;

	// 구르기 관련
	_bool m_bAction = false;

	// 점프 중이니
	_bool m_IsJumping = false;
	_bool m_IsAirDash = false;
	_bool m_IsFalling = false;
	_bool	m_bFallAniOnce = false;

	_float3 m_vMoveDirection = {};
	_int m_iSavedKeyPress = 0;


	// 움직임 가속
	_float m_fAcceleration = 5.0;
	_float	m_fJogAcceleration = 25.f;
	_float m_fSprintAcceleration = 35.f;
	_float m_fGroundPoundAirDelay = 0.f; // 체공시간.

	// GroundPound 관련
	_bool m_bPlayGroundPoundOnce = false;
	_bool m_bCanMove = true;

	// IDLE 상태 길어지면 대기 상태 애니메이션 딜레이.
	_float	m_fIdleTime = 0.f;

	// 상호작용에 의한 움직임.

	// 뭔가 들고있다면
	_bool m_IsPickUp = false;


	// 크기가 달라졌다면
	PLAYER_SIZE m_eCurPlayerSize = SIZE_MEDIUM;
	PLAYER_SIZE m_eNextPlayerSize = SIZE_MEDIUM;
	_float3 m_vScale = {1.f, 1.f, 1.f};
	_bool m_IsSizeChanging = false;

	// 점프관련 변수
	_uint m_iJumpCount = 0;
	_uint m_iAirDashCount = 0;



	// 컷씬이라면
	_bool m_IsCutScene = false;
#pragma endregion

#pragma region Trigger
public:
	void SetTriggerID(GameID::Enum eID, _bool IsCollide);

private:
	GameID::Enum		m_eTargetGameID = GameID::Enum::eMAY;
	_bool m_IsCollide = false;


	_bool m_IsOnGrind = false;
	_bool m_IsHitStarBuddy = false;
	_bool m_IsHitRocket = false;



	_float3 m_vPoints[4] = {};
	_double	m_dTestTime = 0.0;

	void Go_Grind(const _double dTimeDelta);
	void Hit_StarBuddy(const _double dTimeDelta);
	void Hit_Rocket(const _double dTimeDelta);
#pragma endregion

};
END