#pragma once

#include "Client_Defines.h"
#include "Character.h"

BEGIN(Client)

class CMay final : public CCharacter
{
#pragma region Enum_STATE
public:
	enum MAY_STATE {
		/* For.Wall Actions */
		ENTIRE_ANIMATIONS, WALLSLIDE_ENTER, WALLSLIDE_ENTER_FROMDASH, WALLSLIDE_ENTER_NOTJUMPABLE, WALLSLIDE_JUMP, WALLSLIDE_JUMP_VERTICAL, WALLSLIDE_MH, WALLSLIDE_MH_READYTODASH, WALLRUN_LEFT_ENTER,
		WALLRUN_LEFT_JUMP, WALLRUN_LEFT_RUN, WALLRUN_RIGHT_ENTER, WALLRUN_RIGHT_JUMP, WALLRUN_RIGHT_RUN, WALLCLIMB_DOWN, WALLCLIMB_LEFT, WALLCLIMB_MH, WALLCLIMB_RIGHT, WALLCLIMB_UP, 

		/* For.Slide Actions */
		SLIDE_ENTER, SLIDE_ENTER_DASH, SLIDE_ENTER_FALLING, SLIDE_ENTER_GROUNDPOUND	, SLIDE_EXIT_FALLING, SLIDE_EXITTOMOVEMENT, SLIDE_EXITTOWALK, SLIDE_FAST_NEUTRAL, SLIDE_JUMP,
		SLIDE_LEFT, SLIDE_NETURAL, SLIDE_RIGHT,

		/* For.Roll Actions */
		AIRDASH_START, ROLL_FROM_GROUNDPOUND, ROLL_FROM_PERFECTJUMP, ROLL_JOG, ROLL_JOG_FROM_PERFECTDASH, ROLL_PERFECTDASH, ROLL_PERFECTJUMP, ROLL_START, ROLL_STOP, ROLL_STOP_FROM_PERFECTDASH,
		ROLL_WALK, ROLL_WALK_FROM_PERFECTDASH,
		
		/* For.LedgeGrab Actions */
		LEDGEVAULT, LEDGEVAULTSTART, LEDGEGRAB_CLIMBUP, LEDGEGRAB_JUMPBACK_LEFT, LEDGEGRAB_JUMPBACK_RIGHT, LEDGEGRAB_JUMPUP, LEDGEGRAB_MH, LEDGEGRAB_MH_LEFT120, LEDGEGRAB_MH_LEFT180, LEDGEGRAB_MH_LEFT30, 
		LEDGEGRAB_MH_LEFT60, LEDGEGRAB_MH_LEFT90, LEDGEGRAB_MH_RIGHT120, LEDGEGRAB_MH_RIGHT180, LEDGEGRAB_MH_RIGHT30, LEDGEGRAB_MH_RIGHT60, LEDGEGRAB_MH_RIGHT90, LEDGEGRAB_START, 
		
		/* For.Jump Actions */
		DOUBLEJUMP, JUMP_180L, JUMP_180R, JUMP_FALLING, JUMP_FALLING_BCK, JUMP_FALLING_BOOSTED, JUMP_FALLING_BOOSTED_LEFT, JUMP_FALLING_BOOSTED_RIGHT, JUMP_FALLING_BOOSTED_SUCKED, JUMP_FALLING_FWD, 
		JUMP_FALLING_LEFT, JUMP_FALLING_RIGHT, JUMP_FROMDASH, JUMP_FROMDASHSTOP, JUMP_FROMPERFECTDASH, JUMP_FROMPERFECTDASHSTOP, JUMP_LAND, JUMP_LAND_DASH, JUMP_LAND_DASH_JOG, JUMP_LAND_DASH_WALK,
		JUMP_LAND_HIGH, JUMP_LAND_HIGH_JOG, JUMP_LAND_HIGH_WALK, JUMP_LAND_JOG, JUMP_LAND_JOG_JUMP, JUMP_LAND_JOG_JUMP_VAR2, JUMP_LAND_JOG_JUMP_VAR3, JUMP_LAND_PERFECTDASH, JUMP_LAND_PERFECTDASH_JOG, 
		JUMP_LAND_PERFECTDASH_WALK, JUMP_LAND_WALK, JUMP_LONGJUMP, JUMP_LONGJUMP_PICKUPSMALL, JUMP_START, JUMP_START_FWD, SKYDIVELANDING, SKYDIVELANDING_FWD, SKYDIVELANDING_WALK,

		/* For.Grind Actions (레일맵) */
		 GRIND_BTN_PRESS, GRIND_BTN_READY, GRIND_DASH, GRIND_FAST_MH, GRIND_FAST_MH_LEFT, GRIND_FAST_MH_LOOKLEFT, GRIND_FAST_MH_LOOKRIGHT, GRIND_FAST_MH_RIGHT, GRIND_GRAPPLE_ENTER,
		 GRIND_GRAPPLE_TOGRIND, GRIND_JUMP, GRIND_LAND, GRIND_SLOW_MH, GRIND_SLOW_MH_LEFT, GRIND_SLOW_MH_LOOKLEFT, GRIND_SLOW_MH_LOOKRIGHT, GRIND_SLOW_MH_REACHLEFT, GRIND_SLOW_MH_REACHLEFTDOWN, 
		 GRIND_SLOW_MH_REACHLEFTUP, GRIND_SLOW_MH_REACHRIGHT, GRIND_SLOW_MH_REACHRIGHTDOWN, GRIND_SLOW_MH_REACHRIGHTUP, GRIND_SLOW_MH_RIGHT, GRIND_TRANSFER_LANDLEFT, GRIND_TRANSFER_LANDRIGHT, 
		 GRIND_TRANSFER_LEFT, GRIND_TRANSFER_RIGHT, GRIND_TURNAROUND_BOOST, GRIND_TURNAROUND_SLOWDOWN, GRIND_UPSIDEDOWN_ENTER, GRIND_UPSIDEDOWN_EXIT, GRIND_UPSIDEDOWN_FAST_LEFT, GRIND_UPSIDEDOWN_FAST_MH,
		 GRIND_UPSIDEDOWN_FAST_RIGHT, GRIND_UPSIDEDOWN_SLOW_LEFT, GRIND_UPSIDEDOWN_SLOW_MH, GRIND_UPSIDEDOWN_SLOW_RIGHT, 
		 
		 /* For.Crouch Actions (웅크리기) */
		 CROUCH_ENTER_GROUNDPOUND, CROUCH_ENTER_LANDING, CROUCH_ENTER_MH, CROUCH_ENTER_MOVEMENT, CROUCH_ENTER_SLIDE, CROUCH_ENTER_SLIDE_MOVEMENT, CROUCH_EXIT_MH, CROUCH_EXIT_MOVEMENT,
		 CROUCH_EXIT_MOVEMENT_SLOW, CROUCH_MH, CROUCH_WALK, CROUCH_WALK_START, CROUCH_WALK_STOP,
		 
		 /* For.etc (순서 이상하게 들어간 친구들) */
		 ACTIONMH, ACTIONMH_TO_IDLE, EXHAUSTEDMH, EXHAUSTEDMH_TO_IDLE,
		 
		 /* For.Jog Actions (CapsLock 안누를 때 달리기) */
		 JOG, JOG_ACTION_START, JOG_BANK_LEFT, JOG_BANK_RIGHT, JOG_EXHAUSTED_START, JOG_LOOKBACKL, JOG_LOOKBACKR, JOG_START, JOG_START_INMOTION, JOG_START_INMOTION_VAR2, JOG_STOP, 
		 JOG_STOP_ACTION, JOG_STOP_EASY, JOG_STOP_EXHAUSTED, JOG_TURN_LEFT180, JOG_TURN_RIGHT180,
		 
		 /* For.Sprint Actions (CapsLock 눌렀을 때 달리기) */
		 SPRINT, SPRINT_LEFT, SPRINT_RIGHT, SPRINT_START_FROMDASH, SPRINTTURNAROUND, STRAFE_BWD, STRAFE_BWDL, STRAFE_BWDR, STRAFE_FWD, STRAFE_FWDL, STRAFE_FWDR, STRAFE_L, STRAFE_MH, STRAFE_R, 
		 STRAFE_TURNINPLACE_LEFT, STRAFE_TURNINPLACE_RIGHT, 
		 
		 /* For.Walk Actions (걷기가 있나.) */
		 WALK_ACTION_START, WALK_BANK_LEFT, WALK_BANK_RIGHT, WALK_EXHAUSTED_START, WALK_FWD, WALK_START, WALK_START_INMOTION, WALK_START_INMOTION_VAR2, WALK_TURN_LEFT180, WALK_TURN_RIGHT180,
		 
		 /* For.Idle 3개 */
		 MH, MH_TO_ACTION, MH_TO_EXHAUSTED, 
		 
		 /* For.Bounce Actions (점프 발판(쿠션) 밟을 때) */
		 BOUNCE1, BOUNCE2, BOUNCE3, BOUNCE4, PICKUPSMALL_BOUNCE1, PICKUPSMALL_BOUNCE2, PICKUPSMALL_BOUNCE3, PICKUPSMALL_BOUNCE4,

		 /* For.Bump Collide Actions (충돌했을때?) */
		 BUMP_COLLIDE, BUMP_COLLIDE_FALL,

		 /* For.Death Actions (사망) */
		 DEATH_FALL_MH, DEATH_OIL_DROWN, 
		 
		 /* For.GroundPound Actions (점프 후 내려찍기) */
		 GROUNDPOUND_FALLING, GROUNDPOUND_JUMP_HIGH, GROUNDPOUND_JUMP_LOW, GROUNDPOUND_LAND, GROUNDPOUND_LAND_EXIT, GROUNDPOUND_LAND_MH, GROUNDPOUND_START,
		 
		 /* For.KnockDown Actions (넉백) */	 
		 KNOCKDOWN_BACK_LAND, KNOCKDOWN_BACK_MH, KNOCKDOWN_BACK_START, KNOCKDOWN_FRONT, KNOCKDOWN_FRONT_LAND, KNOCKDOWN_FRONT_MH, KNOCKDOWN_FRONT_START, KNOCKDOWN_LEFT_LAND,
		 KNOCKDOWN_LEFT_MH, KNOCKDOWN_LEFT_START, KNOCKDOWN_RIGHT_LAND, KNOCKDOWN_RIGHT_MH, KNOCKDOWN_RIGHT_START,
		 
		 /* For.Lever Actions (좌우 레버(배터리 넣는 로봇)) */
		 LEVER_LEFT, LEVER_RIGHT,
		 
		 /* For.MiniGame Emote Actions (이모트 액션들 ㅇㅇ) */
		 MINIGAME_EMOTES_APPLAUSE, MINIGAME_EMOTES_BOXING, MINIGAME_EMOTES_DANCE_VAR1, MINIGAME_EMOTES_FLIMSYDANCE, MINIGAME_EMOTES_FRONTFLIP, MINIGAME_EMOTES_GIGGLE, 
		 MINIGAME_EMOTES_GUNSLINGER, MINIGAME_EMOTES_ITALIAN, MINIGAME_EMOTES_LOSE_VAR1, MINIGAME_EMOTES_LOSE_VAR2, MINIGAME_EMOTES_LOSE_VAR3, MINIGAME_EMOTES_MACARENA, MINIGAME_EMOTES_SHOULDERBRUSH,
		 
		 /* For.PickUp Actions (등에 짊어지거나 손에 들고있을 때 행동들) */
		 PICKUP, PICKUP_AIM_STRAFE_BWD, PICKUP_AIM_STRAFE_FWD, PICKUP_AIM_STRAFE_LEFT, PICKUP_AIM_STRAFE_RIGHT, PICKUP_AIMSPACE_CENTER, PICKUP_MH, PICKUP_AIMSPACE_DOWN_BS, PICKUP_AIMSPACE_UP_BS,
		 PICKUP_FUSECRAB_PUTINSOCKET, PICKUP_JOG, PICKUP_JOG_STOP, PICKUP_THROW, PICKUP_JUMP_FALLING, PICKUP_JUMP_LAND, PICKUP_JUMP_LAND_JOG, PICKUP_JUMP_START, PUTDOWN, PUTDOWN_INPLACE, 
		 PICKUPHEAVYSMALL, PICKUPHEAVYSMALL_JOG, PICKUPHEAVYSMALL_JOG_START, PICKUPHEAVYSMALL_JOG_START_INMOTION, PICKUPHEAVYSMALL_JOG_STOP, PICKUPHEAVYSMALL_MH, PICKUPHEAVYSMALL_PUTDOWN, 
		 PICKUPHEAVYSMALL_PUTDOWN_INPLACE, PICKUPHEAVYSMALL_JUMP_FALLING, PICKUPHEAVYSMALL_JUMP_LAND, PICKUPHEAVYSMALL_JUMP_LAND_JOG, PICKUPHEAVYSMALL_JUMP_START, PICKUPSMALL, PICKUPSMALL_AIM_MH,
		 PICKUPSMALL_AIM_STRAFE_BWD, PICKUPSMALL_AIM_STRAFE_FWD, PICKUPSMALL_AIM_STRAFE_LEFT, PICKUPSMALL_AIM_STRAFE_RIGHT, PICKUPSMALL_AIMSPACE_CENTER, PICKUPSMALL_AIMSPACE_DOWN, PICKUPSMALL_AIMSPACE_UP,
		 PICKUPSMALL_GROUNDPOUND_FALLING, PICKUPSMALL_GROUNDPOUND_JUMP_HIGH, PICKUPSMALL_GROUNDPOUND_JUMP_LOW, PICKUPSMALL_GROUNDPOUND_LAND_EXIT, PICKUPSAMLL_GROUNDPOUND_LAND_MH, PICKUPSMALL_GROUNDPOUND_START, 
		 PICKUPSMALL_GRIND_TRANSFER_LANDLEFT, PICKUPSMALL_GRIND_TRANSFER_LANDRIGHT, PICKUPSMALL_GRIND_TRANSFER_LEFT, PICKUPSMALL_GRIND_TRANSFER_RIGHT, PICKUPSMALL_JOG, PICKUPSMALL_JOG_START, PICKUPSMALL_JOG_START_INMOTION, 
		 PICKUPSMALL_JOG_STOP, PICKUPSMALL_SPRINT, PICKUPSMALL_SPRINT_LEFT, PICKUPSMALL_SPRINT_RIGHT, PICKUPSMALL_SPRINT_START_FROMDASH, PICKUPSMALL_SPRINTTURNAROUND, PICKUPSMALL_MH, PICKUPSMALL_PUTDOWN, 
		 PICKUPSMALL_PUTDOWN_INPLACE, PICKUPSMALL_SWINGING_APEXTURN_BCK_LEFT, PICKUPSMALL_SWINGING_APEXTURN_BCK_RIGHT, PICKUPSMALL_SWINGING_APEXTURN_LEFT, PICKUPSMALL_SWINGING_APEXTURN_RIGHT, PICKUPSMALL_SWINGING_BCK_FWD, 
		 PICKUPSMALL_SWINGING_BCK_LEFT, PICKUPSMALL_SWINGING_BCK_RIGHT, PICKUPSMALL_SWINGING_ENTER, PICKUPSMALL_SWINGING_ENTER_LEFT, PICKUPSMALL_SWINGING_ENTER_RIGHT, PICKUPSAMLL_SWINGING_EXIT_BCK_LEFT, PICKUPSMALL_SWINGING_EXIT_BCK_RIGHT,
		 PICKUPSMALL_SWINGING_EXIT_FWD, PICKUPSMALL_SWINGING_FWD, PICKUPSMALL_SWINGING_LEFT, PICKUPSMALL_SWINGING_RIGHT, PICKUPSMALL_THROW, PICKUPSMALL_AIRDASH_START, PICKUPSMALL_GRIND_DASH, PICKUPSMALL_GRIND_FAST_MH, 
		 PICKUPSMALL_GRIND_GRAPPLE_ENTER, PICKUPSMALL_GRIND_GRAPPLE_TOGRIND, PICKUPSMALL_GRIND_JUMP, PICKUPSMALL_GRIND_LAND, PICKUPSMALL_GRIND_SLOW_MH, PICKUPSMALL_GRIND_TURNAROUND_BOOST, 
		 PICKUPSMALL_GRIND_TURNAROUND_SLOWDOWN, PICKUPSMALL_JUMP_FALLING, PICKUPSMALL_JUMP_LAND, PICKUPSMALL_JUMP_LAND_HIGH, PICKUPSMALL_JUMP_LAND_JOG, PICKUPSMALL_JUMP_START, PICKUPSMALL_LEDGEGRAB_CLIMBUP,
		 PICKUPSMALL_LEDGEGRAB_JUMPBACK_LEFT, PICKUPSMALL_LEDGEGRAB_JUMPUP, PICKUPSMALL_LEDGEGRAB_MH, PICKUPSMALL_LEDGEGRAB_MH_LEFT120, PICKUPSMALL_LEDGEGRAB_MH_LEFT180, PICKUPSMALL_LEDGEGRAB_MH_LEFT30, 
		 PICKUPSMALL_LEDGEGRAB_MH_LEFT60 , PICKUPSMALL_LEDGEGRAB_MH_LEFT90, PICKUPSMALL_LEDGEGRAB_START, PICKUPSMALL_LEDGEVAULT, PICKUPSMALL_LEDGEVAULTSTART, PICKUPSMALL_ROLL_JOG_FROM_PERFECTDASH, 
		 PICKUPSMALL_ROLL_PERFECTDASH, PICKUPSMALL_ROLL_START, PICKUPSMALL_ROLL_STOP, PICKUPSMALL_ROLL_STOP_FROM_PERFECTDASH, PICKUPSMALL_ROLL_TO_JOG, PICKUPSMALL_WALLSLIDE_ENTER, PICKUPSMALL_WALLSLIDE_ENTER_FROMDASH,
		 PICKUPSMALL_WALLSLIDE_ENTER_NOTJUMPABLE, PICKUPSMALL_WALLSLIDE_JUMP, PICKUPSMALL_WALLSLIDE_MH,
		 
		 /* For. Pull/Push Actions */
		 PULL, PUSH_ENTER, PUSH_EXIT, PUSH_FWD, PUSH_MH, PUSH_STRUGGLE, HOLDBUTTON_ENTER, HOLDBUTTON_EXIT, HOLDBUTTON_MH, PUSHBUTTON_VAR1, PUSHBUTTON_VAR2, PUSHBUTTON_VAR2_MIRROR, PUSHBUTTON_VAR2_SNIPER, 
		 
		 /* For.Skydive Actions (낙하) */
		 SKYDIVE_FALLING, SKYDIVE_FALLING_BCK, SKYDIVE_FALLING_FWD, SKYDIVE_FALLING_LEFT, SKYDIVE_FALLING_RIGHT, SKYDIVE_START, 
		 
		 /* For.Swinging Actions (스윙) */
		 SWINGING_APEXTURN_BCK_LEFT, SWINGING_APEXTURN_BCK_RIGHT, SWINGING_APEXTURN_LEFT, SWINGING_APEXTURN_RIGHT, SWINGING_BCK, SWINGING_BCK_LEFT, SWINGING_BCK_RIGHT, SWINGING_ENTER, SWINGING_ENTER_LEFT,
		 SWINGING_ENTER_RIGHT, SWINGING_EXIT_BCK_LEFT, SWINGING_EXIT_BCK_RIGHT, SWINGING_EXIT_DOWN, SWINGING_EXIT_FWD, SWINGING_FWD, SWINGING_LEFT, SWINGING_RIGHT, 
			
		/* For.PlayRoom_Bute Actions (안쓸듯ㅇㅇ) */
		 BRUTECOMBAT_ATTACK_VAR1, BRUTECOMBAT_ATTACK_VAR2, BRUTECOMBAT_ATTACK_VAR3, BRUTECOMBAT_DASH, BRUTECOMBAT_GROUNDSMASH, BRUTECOMBAT_MH, BRUTECOMBAT_TAKEDAMAGE_HEAVY_VAR1, BRUTECOMBAT_TAKEDAMAGE_HEAVY_VAR2,
		BRUTECOMBAT_TAKEDAMAGE_HEAVY_VAR3, BRUTECOMBAT_ULTIMATWHIRLWIND_MH, BRUTECOMBAT_WHIRLWIND_MH, BRUTECOMBAT_JOG, BRUTECOMBAT_START_FWD, BRUTECOMBAT_STOP, 
			
		/* For.FidgetSpinner Actions (피젯스피너 안쓸듯?) */
		FIDGETSPINNER_ENTER, FIDGETSPINNER_EXIT, FIDGETSPINNER_HOVER_FAST_MH, FIDGETSPINNER_HOVER_FAST_MH_LEFT, FIDGETSPINNER_HOVER_FAST_MH_RIGHT, FIDGETSPINNER_HOVER_SLOW_MH, FIDGETSPINNER_HOVER_SLOW_MH_LEFT,
		FIDGETSPINNER_HOVER_SLOW_MH_RIGHT, FIDGETSPINNER_INAIR_ENTER, FIDGETSPINNER_INAIR_EXIT, LAVALAMPBUTTON,
			
		/* For.PinBall Actions (필수) */
		PINBALL_ENTER, PINBALL_EXIT, PINBALL_HITLEFT, PINBALL_MH, PINBALL_HITRIGHT, PINBALL_LEFT, PINBALL_LEFT_HIT, PINBALL_LEFT_HITSTART, PINBALL_RIGHT, PINBALL_RIGHT_HIT,
		PINBALL_RIGHT_HITSTART, PINBALL_MH_HIT, PINBALL_MH_HITSTART,

		/* For.PlasmaBall Actions (플라즈마공 안할 듯?)*/
		PLASMACUBE_BWD, PLASMACUBE_BWD_LEFT, PLASMACUBE_BWD_RIGHT, PLASMACUBE_BWD_STRUGGLE, PLASMACUBE_BWDLEFT_STRUGGLE, PLASMACUBE_BWDRIGHT_STRUGGLE, PLASMACUBE_ENTER, PLASMACUBE_EXIT, PLASMACUBE_FALL_ENTER,
		PLASMACUBE_FALL_EXIT, PLASMACUBE_FALL_MH, PLASMACUBE_FWD, PLASMACUBE_FWD_LEFT, PLASMACUBE_FWD_RIGHT, PLASMACUBE_FWD_STRUGGLE, PLASMACUBE_FWDLEFT_STRUGGLE, PLASMACUBE_FWDRIGHT_STRUGGLE, PLASMACUBE_LEFT,
		PLASMACUBE_LEFT_STRUGGLE, PLASMACUBE_MH, PLASMACUBE_RIGHT, PLASMACUBE_RIGHT_STRUGGLE, SPINNINGSPACELAMP,
			
		/* 그외의 다양한 상호작용 상태들 */
		ZEROGRAVITY_ADDITIVEROTATION_FWD, ZEROGRAVITY_ADDITIVEROTATION_REF, ZEROGRAVITY_ADDITIVEROTATION_RIGHT, ZEROGRAVITY_BCK, ZEROGRAVITY_FWD, ZEROGRAVITY_MH, VACUUMLAUNCH_ENTER, 
			 
		/* 밸브 돌리기 */
		VALVE_ROTATE_MH, VALVE_ROTATE_R, VALVE_ROTATE_R_SHORT, VALVE_STRUGGLELEFT, VALVE_STRUGGLELEFT_MH, VALVE_STRUGGLELEFTENTER, VALVE_STRUGGLERIGHT, VALVE_STRUGGLERIGHT_MH, VALVE_STRUGGLERIGHTENTER,


	    /* 짜잘한 이동 상태들 */
		WALKIN, CHESSMINIGAME_GESTURES_POINT_VAR1, DASHMOVETO_START, DASHMOVETO_START_INAIR, DASHMOVETO_START_LEFT90, DASHMOVETO_START_RIGHT90, MH_GESTURE_BIG_WAITING_ENTER, MH_GESTURE_BIG_WAITING_MH, 
		MH_GESTURE_SMALL_BRUSHOFFDIR, MH_GESTURE_SMALL_INSPECTNAMILS, MH_GESTURE_SMALL_KNOCK, MH_GESTURE_SMALL_LOOKAROUND, MH_GESTURE_SMALL_STRETCH, MH_GESTURE_SMALL_WATCH,
			 
			 
		 /* 레버 당기는 상태 */
		 LEVERPULL_EXIT_FAST, LEVERPULL_EXIT_SLOW, LEVERPULL_MH, LEVERPULL_START_FAST,
			 
		 /* 아케이드 미니게임 (안쓸듯) */
		 ARCADESCREENLEVER_BCK, ARCADESCREENLEVER_BCKLEFT, ARCADESCREENLEVER_BCKRIGHT, ARCADESCREENLEVER_FWD, ARCADESCREENLEVER_FWDLEFT, ARCADESCREENLEVER_FWDRIGHT, ARCADESCREENLEVER_LEFT, ARCADESCREENLEVER_MH,
		 ARCADESCREENLEVER_RIGHT, ARCADESCREENLEVER_TRIGGER, 
			 
		 /* 로켓 날리기 ㅋ */
		 ROCKETFIREWORK,

		 /* 포탈 탈 때, 코디안넣었나? skydive로 대체하자 */
		 SPACEPORTAL_EXIT, SPACEPORTAL_TRAVEL_MH,

		 /* 컷씬 */
		 CUTSCENE_BEAMUP_INTRO_MAY, CUTSCENE_SPACESTATION_BOSSFIGHT_BEAMOUT, CUTSCENE_SPACESTATION_BOSSFIGHT_EJECT, SPACESTATION_BOSSFIGHT_INTRO, SPACESTATION_BOSSFIGHT_OUTRO, 
		 SPACESTATION_BOSSFIGHT_LASERRIPPEDOFF, SPACESTATION_HUB_SECONDGENERATOR, STATE_END
	};
#pragma endregion

private:
	explicit CMay(ID3D11Device* pDevice, ID3D11DeviceContext* pDeviceContext);
	explicit CMay(const CMay& rhs);
	virtual ~CMay() = default;

public:
	virtual HRESULT	NativeConstruct_Prototype() override;
	virtual HRESULT	NativeConstruct(void* pArg) override;

	virtual _int	Tick(_double TimeDelta) override;
	virtual _int	Late_Tick(_double TimeDelta) override;
	virtual HRESULT	Render(RENDER_GROUP::Enum eGroup) override;

public:
	virtual HRESULT Render_ShadowDepth() override;
public:
	CTransform* Get_Transform() { return m_pTransformCom; }
	CModel*		Get_Model() { return m_pModelCom; }
	void		Update_Tirgger_Pos(_vector vPos);

public:
	void	Set_BossMissile_Attack(); // CBoss_Missile

	// Tick 에서 호출될 함수들
private:
	virtual void KeyInput(_double dTimeDelta);
	void Attack_BossMissile_After(_double dTimeDelta);

private: // 여기에 넣어놓아야 알거 같아서 여기에..		
	void Enforce_IdleState(); /* 강제로 Idle 상태로 바꿈 */

private:
	// 단발성 함수들.
	HRESULT Ready_Component();
	void Add_LerpInfo_To_Model();

private: // Effects
	class CEffect_May_Boots* m_pEffect_GravityBoots = nullptr;

	// 카메라
private:
	class CSubCamera*	m_pCamera = nullptr;


	// 생성 및 소멸 관련
public:
	static CMay* Create(ID3D11Device * pDevice, ID3D11DeviceContext * pDeviceContext);
	virtual CGameObject* Clone_GameObject(void* pArg) override;
	virtual void Free() override;

	

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////    상태 변환 관련 변수들   /////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
public:
	_uint Get_CurState() const;

public:
	// 상태 && 이동
	void Move(const _double dTimeDelta);
	void Roll(const _double dTimeDelta);
	void Sprint(const _double dTimeDelta);
	void Jump(const _double dTimeDelta);
	void Ground_Pound(const _double dTimeDelta);

	// Trigger에 의해 Position 변경해야 할 때.
	void Add_OffSet_Pos(_fvector vAddOffSet);


private:
	// 상태
	MAY_STATE m_iCurState = WALK_BANK_RIGHT;
	MAY_STATE m_iNextState = WALK_BANK_RIGHT;


	// 기본 움직임
	_bool m_bFalling = false;
	_bool m_bWalk = false;
	_bool m_bJog = false;
	_bool m_bDash = false;
	_bool m_bSprint = false;
	_bool m_bOneJumping = false;
	_bool m_bTwoJumping = false;
	_bool m_bClimb = false;
	_bool m_bLedgeGrab = false;
	_bool m_bOnGrind = false;
	_bool m_bRoll = false;
	_bool m_IsTurnAround = false;
	_int m_iSavedKeyPress = 0;
	
	_int	m_iFrameCount = 0;
	_long	m_i10FrameChangedX = 0;
	_long	m_i10FrameChangedY = 0;
	_long	m_iPrePadX = 0;
	_long	m_iPrePadY = 0;
	_bool	m_bPadKeyChangedX = false;
	_bool	m_bPadKeyChangedY= false;

	_float3 m_vMoveDirection = {};
	_bool	m_bMove = false;
	_bool	m_bShortJump = false;
	_bool	m_bLongJump = false;
	_bool	m_IsFalling = false;
	_bool	m_bFallAniOnce = false;

	// 움직임 가속
	_float m_fAcceleration = 5.0;
	_float	m_fJogAcceleration = 25.f;
	_float m_fGroundPoundAirDelay = 0.f; // 체공시간.

	 // GroundPound 관련
	_bool m_bPlayGroundPoundOnce = false;
	_bool m_bCanMove = true;
	_bool m_bGroundPound = false;

	// IDLE 상태 길어지면 대기 상태 애니메이션 딜레이.
	_float	m_fIdleTime = 0.f;


	// 상호작용에 의한 움직임.

	// 구르기 관련
	_bool m_bAction = false;

	// 점프 중이니
	_bool m_IsJumping = false;
	_bool m_IsAirDash = false;


	// 뭔가 들고있다면
	_bool m_IsPickUp = false;


	// 점프관련 변수
	_bool m_bJumpAnimationOnce = false;
	_bool m_bDoubleJump = false;
	_uint m_iJumpCount = 0;
	_uint m_iAirDashCount = 0;



	// 컷씬이라면
	_bool m_IsCutScene = false;


	// 트리거(상호작용) 진행중이라면
	_bool m_IsTriggerPlaying = false;

	// Sprint
	_float m_fSprintAcceleration = 35.f;

#pragma region Trigger
public:
	void SetTriggerID(GameID::Enum eID, _bool IsCollide, _fvector vTriggerTargetPos, _uint _iPlayerName = 0);
	void SetTriggerID_Matrix(GameID::Enum eID, _bool IsCollide, _fmatrix vTriggerTargetWorld, _uint _iPlayerName = 0);

private:
	GameID::Enum		m_eTargetGameID = GameID::Enum::eMAY;
	_float3				m_vTriggerTargetPos = {};
	_bool m_IsCollide = false;
	_float4x4 m_TriggerTargetWorld = {};


	_bool m_IsOnGrind = false;
	_bool m_IsHitStarBuddy = false;
	_bool m_IsHitRocket = false;
	_bool m_IsActivateRobotLever = false;

	/* 혜원::For.DeadLine, SavePoint */
	_bool	 m_IsDeadLine = false;
	_bool	 m_IsSavePoint = false;
	_float3  m_vSavePoint = {};
	_float	 m_fDeadTime = 0.f;
	_float3	 m_DeadLinePos = {};

	/* For.GravityTunnel */
	_bool m_bGoToGravityCenter = false;
	_bool m_IsInGravityPipe = false;
	_float m_fGoCenterTime = 0.f;

	/* For.Valve */
	_bool m_IsEnterValve = false;
	_bool m_bStruggle = false;
	_uint m_iRotateCount = 0;
	_uint m_iValvePlayerName = Player::May;


	_float3 m_vPoints[4] = {};
	_double	m_dTestTime = 0.0;

	// Warp NextStage
	_bool m_IsWarpNextStage = false;
	_float m_fWarpTimer = 0.f;
	_bool m_IsWarpDone = false;
	const _float4 m_vWormholePos = { 0.f, -100.f, -1500.f, 1.f };
	const _float m_fWarpTimer_Max = 2.f;

	// 상호작용 테스트용
	_bool m_IsActivate_End = false;
	_bool m_IsPullVerticalDoor = false;

	// fire Door Dead
	_bool m_IsTouchFireDoor = false;

	// Boss Missile Hit
	_bool m_IsBossMissile_Hit = false;

	// Boss Missile Control
	_bool	m_IsBossMissile_Control = false;
	_bool	m_IsBossMissile_Rodeo_Ready = false;
	_bool	m_IsBossMissile_Rodeo = false;
	_bool	m_IsBoss_Missile_Explosion = false;
	_float	m_fLandTime = 0.f;
	_float	m_fBossMissile_HeroLanding_Time = 0.f;
	_bool	m_IsBossMissile_RotateYawRoll_After = false;

	// touch WallLaserTrap
	_bool m_IsWallLaserTrap_Touch = false;
	_bool m_IsWallLaserTrap_Effect = false;


	void Go_Grind(const _double dTimeDelta);
	void Hit_StarBuddy(const _double dTimeDelta);
	void Hit_Rocket(const _double dTimeDelta);
	void Activate_RobotLever(const _double dTimeDelta);
	void Pull_VerticalDoor(const _double dTimeDelta);
	void Rotate_Valve(const _double dTimeDelta);
	void In_GravityPipe(const _double dTimeDelta);
	//정호
	void Warp_Wormhole(const _double dTimeDelta);
	void Touch_FireDoor(const _double dTimeDelta);
	void Boss_Missile_Hit(const _double dTimeDelta);
	void Boss_Missile_Control(const _double dTimeDelta);
	void WallLaserTrap(const _double dTimeDelta);
	/* 혜원::For.DeadLine, SavePoint */
	void Falling_Dead(const _double dTimeDelta);

	_bool Trigger_End(const _double dTimeDelta);
	_bool Trigger_Check(const _double dTimeDelta);
#pragma endregion


};

END