rmdir /s /q	"ipch"
rmdir /s /q	"Debug"
rmdir /s /q	"Release"
rmdir /s /q 	.\Client\Defaults\ipch
rmdir /s /q 	.\Client\Defaults\Debug
rmdir /s /q 	.\Client\Defaults\Release
rmdir /s /q 	.\Client\Defaults\x64
rmdir /s /q  	.\Engine\Defaults\Debug
rmdir /s /q 	.\Engine\Defaults\Release
rmdir /s /q 	.\Engine\Defaults\x64

del /f /q 		.\Client\Bin\Client.exe
del /f /q 		.\Client\Bin\Client.ilk
del /f /q 		.\Client\Bin\Client.pdb
del /f /q 		.\Engine\Bin\Engine.dll
del /f /q 		.\Engine\Bin\Engine.lib
del /f /q 		.\Engine\Bin\Engine.exp
del /f /q 		.\Engine\Bin\Engine.ilk
del /f /q 		.\Engine\Bin\Engine.pdb
del /f /q		Team3D.VC.db
