rmdir /s /q	"ipch"
rmdir /s /q 	.\Client\Defaults\ipch
rmdir /s /q 	.\Client\Defaults\Debug
rmdir /s /q 	.\Client\Defaults\Release
rmdir /s /q 	.\Client\Defaults\x64
rmdir /s /q  	.\Engine\Defaults\Debug
rmdir /s /q 	.\Engine\Defaults\Release
rmdir /s /q 	.\Engine\Defaults\x64

del /f /q 		.\Client\Bin\Debug\Client.exe
del /f /q 		.\Client\Bin\Debug\Client.ilk
del /f /q 		.\Client\Bin\Debug\Client.pdb
del /f /q 		.\Client\Bin\Debug\Client.iobj
del /f /q 		.\Client\Bin\Debug\Client.ipdb
del /f /q 		.\Client\Bin\Debug\*.cso
del /f /q 		.\Client\Bin\Release\Client.exe
del /f /q 		.\Client\Bin\Release\Client.ilk
del /f /q 		.\Client\Bin\Release\Client.pdb
del /f /q 		.\Client\Bin\Release\Client.iobj
del /f /q 		.\Client\Bin\Release\Client.ipdb
del /f /q 		.\Client\Bin\Release\*.cso
del /f /q 		.\Engine\Bin\Debug\Engine.dll
del /f /q 		.\Engine\Bin\Debug\Engine.lib
del /f /q 		.\Engine\Bin\Debug\Engine.exp
del /f /q 		.\Engine\Bin\Debug\Engine.ilk
del /f /q 		.\Engine\Bin\Debug\Engine.pdb
del /f /q 		.\Engine\Bin\Debug\Engine.iobj
del /f /q 		.\Engine\Bin\Debug\Engine.ipdb
del /f /q 		.\Engine\Bin\Release\Engine.dll
del /f /q 		.\Engine\Bin\Release\Engine.lib
del /f /q 		.\Engine\Bin\Release\Engine.exp
del /f /q 		.\Engine\Bin\Release\Engine.ilk
del /f /q 		.\Engine\Bin\Release\Engine.pdb
del /f /q 		.\Engine\Bin\Release\Engine.iobj
del /f /q 		.\Engine\Bin\Release\Engine.ipdb
del /f /q		Team3D.VC.db
